### ISSUE TITLE
Climatic > Start of Rains

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3529] opened 2017-06-30 12:03 UTC
This is another subtle issue.

I did start of rains for Dodoma in my last session.  Now I did it again with a new definition.
It sent the results to a new file called Dodoma_by_Shiftyear1 rather than adding the column to the original file, which is still there and is called Dodoma_by_Shiftyear.

**Comment by dannyparsons** [comment] 2017-08-11 16:35
@lilyclements is this still an issue?

**Comment by lilyclements** [comment] 2017-08-14 08:25
I can't seem to replicate this. However, I don't believe I fixed this.

@rdstern by "I did start of rains for Dodoma in my last session. Now I did it again with a new definition." do you mean that you did the start of rains for Dodoma, saved as RDS, closed, opened and then did it again with a new definition?

**Comment by rdstern** [comment] 2017-08-14 09:11
I saved the file as an Instat rds file once I had done it once.  Then I returned to R-Instat (the next day) and re-opened the rds file, so it had the data at both the daily and annual levels.  Then I added another definition of the start of the rains.

**Comment by lilyclements** [comment] 2017-08-14 09:30
I can confirm this is still an issue. However, this is occurring with several dialogs when saving RDS files with a `by` data frame. For example, this also occurs with dlgColumnStats.

**Comment by dannyparsons** [comment] 2017-08-14 12:07
This could be an issue with links not being saved properly in the instat object file. I will check.

**Comment by dannyparsons** [comment] 2017-08-16 16:08
fixed by #3813 This was caused by links not being imported on reopen.

**Closed by dannyparsons** 2017-08-16 16:08 UTC
Labels: bug
