### ISSUE TITLE
Order of layers bug in plotting with a simple example

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4899] opened 2018-08-23 12:18 UTC
I wanted to produce the following graph, i.e. a bar chart with a label.

![bar chart with labels](https://user-images.githubusercontent.com/11226469/44524312-4e832180-a6dd-11e8-8098-197c492b9f88.jpeg)

Here are my data
x = 1,2,3,4
y= 0.5, -0.3, 0.7, 0.4
I enter them into a new data frame File > New with 4 rows and 2 columns.  There is a small issue that the variables do not have significant figures, so y is shown initially as 0, -0, 1, 0.  I had to add the significance.  Perhaps there are other options on the data.frame command generated by File > New?

I mane x into a factor.
I then use Describe > General > Use Summaries to get the bar chart.
Then add a layer with geom_label or geom_text.  The x and y are as given above and the label is the y.
This is sort of OK, but the label is in the wrong position.

I want to return to the dialogue to edit the position of the labels.  But the label and the bar have been exchanged, so nothing can be done.  This is consistent with this example, so I hope the problem can be located.
(Incidentally, the way to get the graph as shown was to use the calculator to get y2 = y + 0.2*sign(y).  Then use y2 as the y for the label, keeping y as the label itself.

**Comment by dannyparsons** [comment] 2019-07-11 09:14
duplicate of #5321

**Closed by dannyparsons** 2019-07-11 09:14 UTC
Labels: Menu: Describe, bug
