### ISSUE TITLE
Small changes in climatic boxplots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6102] opened 2020-11-23 11:53 UTC
I have now been using this dialogue quite a lot in preparing a corresponding video.  It has held up quite well, but here are 3 small points:

a) When you first come into the dialogue it correctly completes the control, but not the within year one.  Usually this is the month control.  Could this be added when it exists.  The same lack occus when you press reset.

b) I am not sure what "Vertical x tick markers" is supposed to do?  Is it "Vertical x Labels".  If so, then could the label be changed.  And it doesn't seem to do anything yet.  (I can get vertical x labels from the sub-dialogue.)

c) With multiple stations I have been using the Station control set to `Facet Row`.  When I return to the dialogue it remains set, but if I go to the sub-dialogue and then return, it is still set on the control, but ignored when I press Ok.  If I press on the option, then it is Ok.

d) Could there be an extra up-down control on the right called `Outlier Coefficient`  This is the same as the Coeff value in the sub-dialogue.  It would be the same control as there, with an initial default of 1.5.

**Comment by rdstern** [comment] 2020-12-06 10:17
[ghana_2_stations_for_qcrain.zip](https://github.com/africanmathsinitiative/R-Instat/files/5648575/ghana_2_stations_for_qcrain.zip)

I found more oddities in the climatic boxplot code.  Maybe they can be fixed by @lilyclements, but I suspect it may need a look at the code by @dannyparsons to be efficient.

![image](https://user-images.githubusercontent.com/11226469/101277293-58949580-37ab-11eb-94f4-5a0eaaae317a.png)

This is the graph I wanted.  It was a boxplot for the rainfall, omitting the zero values.

But I started in the wrong data frame, i.e. the last data frame in the attached file that just had 2 rows of data in a single month.
I then moved to the correct data frame, but the dialogue found it diificult to forget the original data frame.

It did give me what I wanted on one occasion, but with the coefficient for the outlier set to 1.5.  I changed it to 3 and then found it had forgotten the condition of omitting values less than 0.85.  I could then no longer find a way (even pressing reset) to get it to include the condition.

I finally succeeded only by copying the closest code from the output window and then editing in the script window.


I suggest it might need a systematic examination of the code?

**Comment by lilyclements** [comment] 2020-12-08 10:27
I followed through this sequence with the data set you've given above. I didn't have issues in changing from the last data frame to the first data frame, but did find the same issue when changing the coefficient on the sub-dialog. To add to this, if I just open the "Boxplot Options" sub dialog (and don't click anything, then close it), the plot/code is no longer omitting zero values.

**Comment by shadrackkibet** [comment] 2022-01-18 08:16
@Ivanluv could you check and report on this?

**Comment by Ivanluv** [comment] 2022-01-18 12:39
@shadrackkibet  the error is not yet fixed

**Comment by shadrackkibet** [comment] 2022-01-18 18:13
> @shadrackkibet the error is not yet fixed

Great, could you please look into it with guidance from @lloyddewit since it is a translation based issue?

**Comment by N-thony** [comment] 2022-01-18 18:21
> the error of faceting controls not remembering their previous setting

@Ivanluv the error is still the error of faceting controls not remembering their previous setting? If so, I think that was fixed already.

**Comment by Ivanluv** [comment] 2022-01-19 06:33
@N-thony could you test on you end

**Comment by N-thony** [comment] 2022-01-19 10:40
> @N-thony , the facetting error is still present on my end after updating my master. Could you test on you end

@Ivanluv I did the test again and was still not able to reproduce the error. I have also updated my master branch.
Here is the dialog on reopen
![image](https://user-images.githubusercontent.com/68591383/150114396-f620650d-c9c0-46bd-bb2c-5d9ef0c71ecf.png)

**Comment by Ivanluv** [comment] 2022-01-19 10:55
Sorry, this works now. Am not sure what I might have missed on my previous test

**Closed** 2022-01-19 10:57 UTC
Labels: Climatic
