### ISSUE TITLE
Corrections and an oddity in the climatic data entry dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7279] opened 2022-03-08 08:03 UTC
I have been using the Climatic > Tidy and Examine > Daily Data Entry dialogue as an editing facility to correct daily data for 2 stations in Tajikistan.  This is following the quality control, that showed a number of oddities.  For example there were 97 occasions with tmax <= tmin.  I now need to correct the data.  I am unable to get access to the paper records, and need to see the odd days in context.
I am finding the data entry tool to be excellent for this in a variety of ways.  

![image](https://user-images.githubusercontent.com/11226469/157190394-c2c69e69-b986-4006-b184-09ecd3c41624.png)

There are a couple of small improvements I suggest, and then an oddity that is shown here - a bug, perhaps to be found.
a) Please change the menu name to `Daily Data Editing/Entry` .  
b) And make the same change in the title of the dialogue.
c) When you return to the data entry after coming out of data entry it always asks if you really want to, because you will lose what was entered earlier.  Here is an example of the message:
![image](https://user-images.githubusercontent.com/11226469/157191414-12c1d2a7-f7e0-4ed7-9d68-a2112ad8d4e9.png)

Now, once you have entered, or corrected data, the number of corrections is shown in red at the bottom.  But the message appears whether, or not, you have made any corrections.  In the example above, I went into the sub-dialogue, then came straight out, and am now returning.  The message should not be given unless there are values to correct.

I hope these are quick and easy to do, because they include an edit to frmmain.

d) There is a bug that has just appeared.  It is that yellow box in the figure above.  This has appeared and is very annoying.  It is very persistent.  I have reset the main dialogue, and also the sub-dialogue.  But it has just appeared (I now realise it is in the master I should say - I was using Version 7.3 earlier??? and didn't get this!)    I'll start again - with the master, and see if it is a consistent problem.  Then - if so, I'll check with other versions.

I am suggesting @N-thony could fix at least a) to c) easily.  I really don't understand d) and will check further.

**Comment by N-thony** [comment] 2022-04-16 09:55
@rdstern I'm not able to reproduce item d), please check again otherwise we can close this?

**Comment by rdstern** [comment] 2022-05-26 10:42
@N-thony In the 2 recent workshops this dialogue seems useful.  I still need to check for the oddity above and suggest we may find more quirks as we use it more.  So while a developer makes small improvements I hope that @Wycklife can make serious use of the dialogue, and I think more oddities will appear.  It is quite sensible to use it for the entry of some of the additional data from the Kenya stations and also to make corrections.  Here are small tasks so far.

a) The default is by month.  Go into that and (if you change a day, or more) and add a comment - or two - then you can update, i.e. press Ok.  But I sometimes don't want to change, just add a comment.  I would like to update the comments even if just a comment is added.  Currently this is not possible.
b) When I click on Range and choose, e.g. 3 months it does not keep that setting.  It resets to Month when I re-open the dialogue.
c) When using range I was not able to add a comment the add comment was disabled.

I will be surprised if we don't find more as we use it.

**Comment by N-thony** [comment] 2022-05-30 08:12
> @N-thony In the 2 recent workshops this dialogue seems useful. I still need to check for the oddity above and suggest we may find more quirks as we use it more. So while a developer makes small improvements I hope that @Wycklife can make serious use of the dialogue, and I think more oddities will appear. It is quite sensible to use it for the entry of some of the additional data from the Kenya stations and also to make corrections. Here are small tasks so far.
> 
> a) The default is by month. Go into that and (if you change a day, or more) and add a comment - or two - then you can update, i.e. press Ok. But I sometimes don't want to change, just add a comment. I would like to update the comments even if just a comment is added. Currently this is not possible. b) When I click on Range and choose, e.g. 3 months it does not keep that setting. It resets to Month when I re-open the dialogue. c) When using range I was not able to add a comment the add comment was disabled.
> 
> I will be surprised if we don't find more as we use it.

@EstherNjeriLiberatta please implements items a) and b). c) isn't a problem, you just need to define key before adding a comment in the data, perhaps add a tooltip to `Add comment` in the Comment subdialogue.

**Comment by N-thony** [comment] 2022-07-11 07:41
@lilyclements @EstherNjeriLiberatta could we have a quick discussion today?

**Closed** 2022-08-16 08:49 UTC
Labels: Climatic
