### ISSUE TITLE
Models - simple one variable and two variable

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1942] opened 2016-10-25 11:11 UTC
In the Model > One Variable > Fit Model we do a lot of general things.  But we don't have the simple (exact) model fitting that is usually done at the start of statistics courses, i.e. one-sample normal, leading to a t-confidence interval and test.  Not binomial, or Poisson.

I suggest these be added.  Here I consider one sample and the next entry in this thread is for 2 samples.

In the dialogue for One Variable > Fit Model, I suggest a radio button at the top with General and Special as the two options.  I don't care what the default is, but suppose David would want General!

With "Special" selected there are just 3 distributions, namely Normal, Binomial, Poisson.  In each case I think they produce an object, which can be saved in the usual way.  

The mosaic package has a wrapper for the t.test and binom.test commands and so we will probably use those, because we are loading mosaic for pdist, qdist and plotdist anyway.  It seems to work OK.  There would now be fewer options, so the usual sub-dialogues would be disabled.  But we may want a special sub-dialogue (or one or two more options on the main dialogue), for example to choose the value for the null hypothesis. 

Mosaic does not have a poisson.test, but there is one in the stats package.

**Comment by lilyclements** [comment] 2016-10-25 11:40
Sounds good. I'll get started on for One Var > Fit Model? I'll have a look on R at tests and such as well.

With "Special" you mentioned the three distributions to choose from are Normal, Binomial and Poisson. Do you mean to include the T Distribution in here?

**Comment by rdstern** [comment] 2016-10-25 11:40
We also should be including the two-sample problems.  There are some interesting issues here.

For binomial mosaic has prop-test which generalises the same function in the stats package.  And t-test is also available for 2 samples.  Also poisson.test is available for 2 samples.  So that's all OK!

This will become an added set of special options in the Model > Two Variables > Fit Model dialogue, perhaps again radio buttons with General and "2-samples".

The layout of the data for us will be (usually) a single column with a factor column giving the 2 groups.
The distributions will be Normal, Binomial, Poisson as before.  

If the data are in separate columns then they would be in separate data frames (unless they are paired).  Initially we could ignore this option, unless we want to offer the option of the data selector that includes the data frames. 

They could be in the same data frame, and then we would do the paired t-test, which is an option of the t.test.  We might not allow that option for binomilal, though it is available possibly through the PropCIs package, and perhaps elsewhere.  We would not allow it for Poisson.  If you wanted to do this for Poisson, then it is an example of a glm!

Interesting!

Roger

**Comment by lilyclements** [comment] 2016-10-26 15:22
We have an interesting predicament. So, while we have the wrapper on R when applying 'mosaic' (which makes binom.test much nicer and easier!), on our R-Instat it is not using that version and is only using the binom.test in the stats package.
This means it is bringing up an error code and won't allow the columns if they are
* Greater than length 2
* Not integers
* Negative
(And maybe other requirements which I am not aware of)

Is there a way to ask R-Instat nicely to use the mosaic package and not default to ignore the wrapper?

**Comment by volloholic** [comment] 2016-10-26 15:28
This shouldn't be a problem as we can choose what we want it to do. Should we Skype?

**Comment by lilyclements** [comment] 2016-10-26 15:30
Ah great. Yes sure, do you have my skype? It's Lclements1004@outlook.com

**Comment by lilyclements** [comment] 2016-10-27 11:37
I've implemented the codes for One Sample Hypothesis Tests so I'll get started on Two Sample shortly. I just wanted to add something extra in and so thought I should check. On the Poisson Test, by default it uses the first one to count, that is, the lowest number or the first factor name, etc.
So, I want to be able to add in the option to change this. This means that the code would become

poisson.test(x= count (*variablename* == *number*)    (or the number can have quotations around it)
or if it is a factor
poisson.test(x= count (*variablename* == *"factorname"*)

If the consensus is it is not necessary then I won't worry about it. I just think it could be a helpful tool.

**Comment by lilyclements** [comment] 2016-10-27 13:07
@rdstern , you mentioned for two-sample hypothesis tests you would like a single column and a factor column. Alternatively perhaps two single columns to compare numerical variables. I just want to check I've caught up because I am a little confused. So, we could have three scenarios for a t.test:

Numerical Column split by Factor (t.test or prop.test)
Numerical Column vs Numerical Column from same dataset (t.test only)
Numerical Column vs Numerical Column from new dataset (t.test only)

In which case, is the idea to have two receivers (as there already is)
The first accepting numerical variables if it is a t.test or prop.test
The second, if a factor variable is input then the code run is t.test(first ~ second) (and similarly for prop.test)
If Normal Distribution is selected then a numerical variable can be input so the code run is
t.test(x=first, y=second)
Otherwise, only allow factors here.

Then, alternatively if Normal is selected, some form of checkbox to use a different dataset for the second column which then brings up either a dataframe or a cbobox with GetItemTypes as the dataframes and our receiver becomes a cbobox with GetItemTypes as columns from the above dataframes?

Then finally the usual options - mean/probability/rate, Confidence Interval, etc?

Or am I over complicating this and we just want the Single Receiver and Factor Receiver so it can work for both Prop.test and t.test?

**Comment by rdstern** [comment] 2016-10-28 07:26
I think you will get further with these issues on discussion with David.  Let me answer a few of your points:
1.  We don't yet load Mosaic - which we will in the next version of R-Instat.  So then it should default to the Mosaic version.  For now you could try **t_test**, rather than **t.test**.
2. The Mosaic version added the feature - which we want - of starting with the data column.  I think the basic functions assume the summary data.
3.  Now that could cause a problem with the Poisson, because Mosaic doesn't have a function for this.  So you could leave this for now.  But it can be done for the one-sample case by poisson.test(length(x), mean(x)) I think  -where x is the column.
4.  With the columns for the one-sample case I suppose all the residuals apply!  So perhaps you could also do (behind the scenes) the fitdistrplus object and then allow access to the residuals.  You would not print out any of the results from fitdistrplus.  Check this with David.  (It may be that we would only want this nice residual stuff in the general case, but I think it could be neat here!)

4. For the 2-sample case I notice that Poisson does this!  It makes it binomial, so that could be added, though it is lower priority.  Again you will have to produce the summaries, as in the 2nd example for Poisson.test.
5. In the 2-sample case I am mainly interested in the situation where there is one numeric column - with the data - and one factor column, which has 2 levels.  (There could be more than 2 levels, but filtered, so only 2 are active.)
6.  If there are 2 data (numerical) columns then we assume paired.
7.  The third option is one column from each of 2 data frames.  Danny was quite keen on this, and we do have other work that uses more than one data frame.  I would leave this option for now, but David may have other ideas!

Hope this helps

Roger

**Comment by rdstern** [comment] 2016-11-04 21:07
Great getting the one variable and 2 variable exact working.

Here is what I have observed so far.  I used the usual survey data (of course). 

a) The one variable dialogue has now just the 3 distributions.  The 2 variable still has the whole set.  That needs the same change.
b) Could you change the label, so it says **Mean (under H0)** (ideally subscript 0) or **Mean 0.00 Under H0** or **"Under Null Hypothesis"**.  For 2 variables there isn't a label at all.  It could be "Mean Difference (Under H0)".  I haven't checked yet with the other distributions.
c) In the one variable, the graph is done automatically.  I suspect it takes whatever option  is enabled from the general.  Could there (instead) be simply a checkbox on the main dialogue - default unticked.  If ticked, then it always just does the combined graph.
d) In the 2 variable I tried first with Variety - which has 3 levels.  It told me that only 2 levels were allowed - which is good.  I wonder (possibly in the longer term, whether that sort of error will be trapped earlier, or the message will more obviously be a controlled one.
e) Still on 2 variables I now filtered to just 2 levels of the Variety factor.  Then it doesn't give an error, but it also doesn't give any results!  It gives a good set of R commands!
e)   I tried Bernoulli. with the condition being > 40 for the yields.  It gave an error, but I think it gave the results.  Perhaps the error is related to the graph.  I don't know what the graph should be for Bernoulli, so perhaps we don't have one - at least if that is causing the problem.
f) Please can you check on the "dialogue memory" when you return to the dialogue. I have only looked so far at the one variable dialogue.  After Bernoulli I came back and the dialogue stays on Exact, but I think the distribution returns to Normal.  When I do Bernoulli again it has not "remembered my 40.
g) For the 2 variable Poisson I just put 2 columns in and it  worked but I don't understand the results.  When I tried Bernoulli with Yield it didn't ask for the probability of success.  For now, for the 2-variable, I wonder if we just do the normal distribution and leave the others for later.

Roger

**Comment by lilyclements** [comment] 2016-11-04 21:41
Two Variables must have not been merged when you downloaded the most recent version, since they do now have labels and only display the three distributions at the moment! Also the code runs successfully for it now (it stopped temporarily since I changed some stuff in ucrDistributions!)
I'll change the labels though to saying how it's under the null. I'll sort that out tomorrow if that's okay!

c) Sure thing. This graph does the combination - for a continous distribution it is the four graphs and for the discrete it is the two. Do you want the checkbox to display nothing if it is unticked?

d) I was aware of this error and it will get solved eventually!

e) This should not be an issue anymore now Two Variable Hyp has been merged in

e2) was this graph on One Variable? There is an issue there that I wanted to discuss with you. The error coming up is for the likelihood plots for a certain number of distributions (I know which ones and why!)

f) I'll have a look into this!

g) 2 Variable Poisson will hopefully work now that Two Variables has been merged in

Lily

**Comment by lilyclements** [comment] 2016-11-04 21:57
Another issue that there is - which is on One-Variable is with Bernoulli.
If a factor is selected on Bernouli, then you tick the 'Modify Conditions for Success' check box, then a combo box comes up. At the moment this combo box is empty since there isn't yet a way to have the options in the combo box to be the levels within the factor chosen. Perhaps for the meantime I could make it into an option where we can write in the factor although if the user doesn't write it in correctly then it'll have an error?

**Comment by rdstern** [comment] 2016-11-05 04:31
With the 2-variable dialogue, when set to Exact the second column can now only be a variate.  (That's not the condition for "General".  Most of the use of this dialogue for exact will have the second column as a factor, so that needs to be possible.

In the Poisson  (2 variable) you have "Rate".  My understanding is that the label should be "Rate Ratio".
In the Bernoulli (2 variable) I assume the null hypothesis is (usually) for the zero "Difference in proportions", just as it is for the "Difference in means" for the normal.  
In the Bernoulli there isn't a facility (as there is, in the one variable) for the criterion for success.  Even if you can't (yet) cope with factor levels in the dialogue it would be good to be able to cope with the numerical columns.

**Comment by rdstern** [comment] 2016-11-05 09:30
I have discovered some "interesting" - positive features for the Bernoulli.

1) First a trivial one - please add an extra l into the name.
2) Then here is what I tried.  I produced Calc1 = Yield>40 from Organise > Column: Calculations > Calculate
3) I then did it again into Calc2.  Then I made Calc2 into a factor.  I assume this makes the "values" 1 and 2, while they are 0 and 1 in Calc1.
4) Then I tried these with your Bernoulli - one sample.  I think then for the logical column (Calc1) the default is for TRUE to be a success.  It is the opposite way round for Calc2.
5) Then for Calc2 I modified the condition for success to say it was a success if X=2.  That worked fine.  So (while or if we wait for something better) we can already use your existing dialogue with the integer values behind the factor.  

Not so easy to try with the 2 variable, because I can't (yet) put a factor as the second column.  

This would still mean that some factors could have curious combinations we can't cope with.  But that's ok, because we can always use our calculator first.

Roger

**Comment by lilyclements** [comment] 2016-11-05 12:10
Okay, I wasn't aware of that bug in 2-variable so I will fix that today!

I will change these labels as well to Rate Ratio, Difference in Proportions and Difference in Means.
I also will change the one-var labels to something along the lines of "Under Null Hypothesis"

I will add in a criteria for success. Would we want this in the beta release?

Interesting! I thought Bernoulli was 2 l's, but everywhere was using one and I checked and it used 1, it must have been an american site or something! I will sort that out!

**Comment by lilyclements** [comment] 2016-11-05 12:20
For two-variable sdg do we want
Normal: column1 - variate, column2 - factor or variate
Binomial: column1 - factor, column2 - factor
Poisson: column1 - variate, column2 - variate

Thanks,

**Comment by rdstern** [comment] 2016-11-05 14:51
The default "layout" is that there is a single data column, with a second column being a factor with 2 levels.  That's for all cases.
The alternative (in any of the cases) is 2 data columns of the same length - have to be if they are in the same data frame.  Then the data may (is likely to be) paired.  So that will be a question (after the beta release) when this part is enhanced.  For now these are just alternatives.

**Comment by lilyclements** [comment] 2016-11-05 15:16
With the R Code for Poisson, it would only allow for the second variable to be numeric. Or, at least I can't find a way that would allow it to not be numeric because we are comparing two rates?
Additionally, if the user may wish to compare two numeric unpaired variables for a t-test to test for equal means so wouldn't we offer the option of a variate here as well?
Sorry! I'm just getting a little confused about this second data column,

**Comment by lilyclements** [comment] 2016-11-05 15:23
For the time being I have disabled two options which were causing issues. Firstly, on One Var Fit Model, the residuals plot does not come up if Binomial is selected. This is because of an error so I've made it temporarily that this will not plot if Binomial is selected.
Secondly, on Two Var Models, the code sometimes does not run if check save model is checked. So, I disabled this to get on with the bug hunt. I think Danny might look at the code to see why the issue is happening?
I can spend more time exploring it myself - I'm just not too sure how else to help the bug at this stage.

**Comment by rdstern** [comment] 2016-12-01 13:46
There is still work to be done on the Model > One Variable > Exact dialogue. This is in addition to getting the dialogue working again for the Bernoulli and Poisson.

1) The EnvStats package has some features of interest, though it is also pretty long!
2) The hTest.object is interesting.  It is an object for all the simple hypothesis testing commands, including those from R itself.  So we can save any of these objects.
3) We should add the facility to estimate and test the variance of the normal (in addition to the t.test that is already there.  The EnvStats package has 2 possibilities, namely **varTest** for one sample (not to be confused with var.test in the main stats package, which is the F-test for 2 samples).  An alternative is the **enorm** command also in the EnvStats package.
4) In addition to the distributions so far, we also want to have **None**.  This is for non-parametric methods, and will replace the special dialogue we have so far.  There are 2 obvious alternatives and we should include both, namely **None-Sign** and **None-Wilcoxon**.  The Sign test could use the special SignMedian package.  The Wilcoxon for one sample could use wilcox in the main stats package.  Could also look in the EnvStats package.

There may be one or two other single sample tests for trend to add, but I think that is most of what we need for the single variable.

**Comment by rdstern** [comment] 2016-12-01 13:52
The Model > Two Variables > Fit is (I think) more complicated, because there are many options.

1. I suggest that the second "button" be changed from "Exact" to "2-Sample".
2. We add the var.test to the normal, which does an F-test to compare 2 variances, just as there is already the t-test to compare 2 means.
3. We will have the Mann Witney test - same as the 2-sample Wilcoxon.  So we have "None-Wilcoxon" there too.
This is all relatively simple.  What gets more complicated is the general case, where there are many more options than we have currently.  We should look at the possibilities here in detail.  The EnvStats package gives some ideas.

**Comment by lilyclements** [comment] 2016-12-01 13:53
Bernoulli and Poisson are working now, I'm just waiting for it to be merged in.
I'll have a look into these packages and adding these features!

**Comment by rdstern** [comment] 2016-12-01 14:33
Just to be clear.  I think for the 2 variable case we could have a special option, as mentioned above - called "2-sample".  In that case the first Variable would be a variable - as now.  The second would be a factor with 2 levels.  It might even be labelled as such.  So, for the survey data set this could apply if the variety had been filtered to have just 2 of the 3 levels, or we did the analysis by village and had filtered to have just 2 villages.  Whether the selector can be made to choose just this subset of factors, or we check (in the receiver) once a factor has been selected is for discussion.  It could be simple (and clean) in the selector, but might give a simpler and clearer error message once the receiver has the factor.  Then you would not enable OK, but might leave the factor there.  In that case you could go to the data options and set the filter there, and all would be OK.

Roger

**Comment by lilyclements** [comment] 2016-12-09 15:02
My understanding of the Mann Witney test is that it does not assume a normal distribution. Under which selected distribution should I put this option, therefore?
Additionally, do we want to include (later) an option for a paired Wilcoxon test?

**Comment by rdstern** [comment] 2016-12-09 18:51
That’s right.  In the same thread I am suggesting that this comes under Distribution “None”.  (I am replying in the e-mail, because I can’t see your comment in the thread.)

Yes eventually we will have the paired situation.  But now the standard layout – for 2 samples is a single data column with a second factor column (2 levels) that defines the groups.  That doesn’t lend itself to the paired case.

Roger

**Comment by dannyparsons** [comment] 2017-06-15 17:51
I believe this is implemented, at least initially, can this be closed @lilyclements?

**Comment by lilyclements** [comment] 2017-06-15 19:04
Yep this can be closed. We still want to offer a paired t-test but I think other than that this is good.

**Closed** 2017-06-15 19:08 UTC
Labels: bug, enhancement, Menu: Model
