### ISSUE TITLE
Bug on simulation of samples of n>1000

### ISSUE THREAD

**Issue by MainaJohnO** [africanmathsinitiative/R-Instat#4306] opened 2017-12-07 08:36 UTC
![capture_bug_simulating_samples_greater_than1000](https://user-images.githubusercontent.com/32262789/33705490-953038d8-db41-11e7-8a7e-5db779639b11.PNG)
In regard to the eSMS assignments for R-instant during the review of topic 3 - Assignment1, under section(2.1) question 3 on simulation of samples when I try generating a sample of n=4000, the attached bug pops up. 
 An indication that the Rice_Yield_Population data sets we are using is not up to date. May be an update of the Rice_Yield_Population data sets is required
 The bug happens even if the sample size n=4000 is the first one to be generated. Trying to generate a sample of n=1001 the bug still pops up a clear indication that the bug pops up for any sample size of n>1000.

**Comment by Patowhiz** [comment] 2017-12-19 10:11
@MainaJohnO Did this happen when the number of columns =1 or even when the columns are multiple?

**Comment by MainaJohnO** [comment] 2017-12-19 12:52
It happens when the number of columns=1, seems when the columns >1 it can
work

**Comment by dannyparsons** [comment] 2017-12-20 18:34
Yes we determined the issue with @Patowhiz and @shadrackkibet

**Comment by dannyparsons** [comment] 2018-01-19 09:12
This should be fixed now by #4322. @MainaJohnO Can you check and close if it's ok?

**Comment by MainaJohnO** [comment] 2018-01-22 06:23
# Code generated by the dialog, New Data Frame

data <- data.frame(data=matrix(data=NA, ncol=1, nrow=1001))
InstatDataObject$import_data(data_tables=list(data=data))

rm(data)

I have tried out to generate a sample of size of n=1001 and it does not run
successfully. the code is as above and the bug that pops up is attached.

@Patowhiz <https://github.com/patowhiz> and @shadrackkibet
<https://github.com/shadrackkibet> the issue is not fixed

**Comment by dannyparsons** [comment] 2018-01-22 11:04
It seems to be working fine for me now. Are you using the latest version? @Patowhiz can you check this with @MainaJohnO?

**Comment by shadrackkibet** [comment] 2018-01-22 11:52
@MainaJohnO  is using our last version which was released when this was not yet fixed.
I checked this with him from the current master and we confirmed it is now working fine.So this can now be closed.

**Comment by dannyparsons** [comment] 2018-01-22 12:06
Great thanks, it would be good if @MainaJohnO can have access to the current development version through Visual Studio for testing.

**Closed by dannyparsons** 2018-01-22 12:06 UTC
