### ISSUE TITLE
That graphics order of levels bug again

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5397] opened 2019-07-01 09:03 UTC
**Describe the bug**
With 2 levels the order sometimes changes and then can't be edited.  Here is a very simple example.
The data are as follows:
[Dodoma_normals.zip](https://github.com/africanmathsinitiative/R-Instat/files/3344694/Dodoma_normals.zip)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Describe > General > Use Summaries
2. Do a bar chart  of the Mean rain by Month
3. Use Plot options and Add layer - add a Label.
4. The label is also the Mean rain
5. Get the graph

It comes with many decimals and overlaps to top of the bars.  Don't worry about that.  
6. Return to the dialogue and the Layers again.  The Label is now before the bars in the list.  

For reference here is an example that I am aiming for:
![image](https://user-images.githubusercontent.com/11226469/60424016-b48ae000-9bef-11e9-854f-9a9036d6a382.png)

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem, particularly of error messages.

**R script or commands**
If applicable, add the R commands from the output or log window that produced the problem. Even better, save the log file and attach it to the issue.

**Details (optional):**
 - OS: [e.g. Windows 7]
 - R-Instat Version [e.g. 0.4.22]

**Additional context**

**Comment by dannyparsons** [comment] 2019-07-11 09:14
duplicate of #5321

**Closed by dannyparsons** 2019-07-11 09:14 UTC
Labels: Menu: Describe, bug, duplicate
