### ISSUE TITLE
Proper setting of the station pull down to remember the station selected when you return to the dialog in Climatic>Tidy and Examine>Daily Data Entry dialog

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6450] opened 2021-05-04 13:43 UTC
**Describe the bug**
I have been using the Daily Data Entry dialog to enter data for Maseno and Kibos stations but I keep on selecting the station every time I want to enter a new record.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Climatic>Tidy and Examine>Daily Data Entry.
2. Select the the station to be entered from the station pull down (Kibos) and add the the element to the receiver.
3. Select the dates for the entry
4. Click on the Data Entry button and Click return. The station pull down returns to the default station (Achego).
**Expected behaviour**
I think when I click return the pull down should be showing the station selected before.

**Comment by shadrackkibet** [comment] 2021-05-04 16:11
@N-thony this should be an easy one to fix. Can you fix it?

**Comment by rdstern** [comment] 2021-05-07 09:49
This was a problem in Version 7.0, but I thought it was already fixed by @N-thony in Version 7.1?  Perhaps not?

**Comment by N-thony** [comment] 2021-05-07 09:53
> **Describe the bug**
> I have been using the Daily Data Entry dialog to enter data for Maseno and Kibos stations but I keep on selecting the station every time I want to enter a new record.
> **To Reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Go to Climatic>Tidy and Examine>Daily Data Entry.
> 2. Select the the station to be entered from the station pull down (Kibos) and add the the element to the receiver.
> 3. Select the dates for the entry
> 4. Click on the Data Entry button and Click return. The station pull down returns to the default station (Achego).
>    **Expected behaviour**
>    I think when I click return the pull down should be showing the station selected before.

@Wycklife following this, I couldn't reproduce the problem.

**Comment by Patowhiz** [comment] 2021-05-07 13:00
@N-thony and I looked at this bug. The cause of the bug is in `ucrInputFactorLevels` control, it clears its contents when any change is made in the  linked `ucrReceiverSingle` control even during reopening of a dialog.

**Comment by rdstern** [comment] 2021-05-12 14:52
@Wycklife I think this (#6450) is now fixed and should be merged soon.
It has exposed that the Kenya data files in the R-Instat library are not the most up-to-date ones.
Can you also sort out an issue so they are updated for the next version of R-Instat.  Thanks

**Closed** 2021-05-13 09:28 UTC
Labels: Climatic, bug
