### ISSUE TITLE
Calculator error when running dialog with numbers as inputs

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#1792] opened 2016-09-22 13:35 UTC
@dannyparsons , @rdstern 

If I type 555 in r and press enter, 555 is returned as output but if the same is done and you ask the calc to give the result in output window an error occurs as shown in the attachment.

I am not sure if this is what we want?
![calc error](https://cloud.githubusercontent.com/assets/13945088/18750128/9108be02-80e2-11e6-93b8-c7198837b1eb.PNG)

**Comment by rdstern** [comment] 2016-10-08 16:34
I am not sure whether anything has yet been done on the previous message, which was noted as a bug?
I would like to continue (also) enhancing the calculator - and also fixing bugs!
1. I like the fact that Try seems to be sort of working.  I say "sort of", because I used it when it was OK, and that was fine.  When I came back to the dialogue it (of course?) still had that result, because it starts there.  I suggest Try should perhaps be cleared each time.  Anyway I pressed it again and it gave me an error.  In general the Try function isn't simple.  I think it should also clear if any change is made to the formula.  
2. Could there be a help button below each of the extra keyboards.  they each have their own ID which is Maths (126), Logical (127) Statistics (can we change the name to "Summary" (128, Strings (338, Probability 120 and dates 130.
3. This may need some discussion with Danny and possibly David, but could there be a drop-down perhaps below the logical keyboard?  This should (only) have the factors that are in the formula so far and it would give the levels.  It should enable you to choose a level for a factor, which is then put into the formula - as "level", i.e. the level with quotes round it, e.g. "Variety.=="OLD""

Roger

**Comment by Lunalo** [comment] 2016-10-09 11:08
Hi Roger,

Thanks for the reminder.

I tried fixing the Try but it seems Danny will have to improve on
something. I can still go ahead and fixing the clearing part.

I will fix for help for each keyboard which I think it is a great idea but
am not sure if we still need a general help for the dialog.

Lastly, The idea of having levels of a factor, I am not sure if we need a
list box or combo box. I can suggest list box so that the user can view all
the levels of a factor at once.

Thanks.

**Comment by dannyparsons** [comment] 2016-10-09 11:41
I will look into the Try on the calculator now.

**Comment by Lunalo** [comment] 2016-10-11 09:01
@rdstern  The help for the groups is working fine @ #1877

**Comment by dannyparsons** [comment] 2017-01-03 14:13
This is still a bug. Specifically if you type in a single number into the calculator and don't save the result as a column you get an error because `capture.output(11)` produces an error in R. 
Not sure why and may be worth posting in a forum.
I think it's fairly uncommon so not urgent to fix.

**Comment by shadrackkibet** [comment] 2021-01-29 14:22
Same issue as #6018. There seems to be a solution to this in the next version of R see https://github.com/HenrikBengtsson/Wishlist-for-R/issues/54

**Comment by shadrackkibet** [comment] 2021-01-29 15:36
Confirmed that this is fixed in the upcoming version of R (4.1.0)
![image](https://user-images.githubusercontent.com/26301973/106294970-e7300b00-6260-11eb-97dd-3ea6197de91b.png)

**Comment by shadrackkibet** [comment] 2021-05-19 12:43
Just to note that R version 4.1.0 has now been [released](https://www.r-project.org/). Therefore once we upgrade this bug should be fixed!

**Comment by shadrackkibet** [comment] 2021-05-26 17:38
We have now updated to R 4.1.0

**Closed by shadrackkibet** 2021-05-26 17:38 UTC
Labels: Menu: Prepare, bug
