### ISSUE TITLE
Problem deleting the only data frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5613] opened 2019-12-09 09:22 UTC
The bottom **_right-click Delete_** calls the **_Prepare > Data Object > Delete Data Frames_** dialogue.

This is generally working well, but gives a nasty message if you try to delete the only (or possibly also all) the data frames.  It also appears not to work, but I think it sort of does, because the data frame disappears when a new one is opened.  It possibly doesn't know what to do when there is no data frame left. 
It is easy to delete all (or the last) data frame - use **_File > Close Data File_** instead.

Could this dialogue trap this situation.  It would ideally either call the File > Close Data File code, or at least refuse and give the message for the user to use File > Close Data File option instead.

**Comment by lloyddewit** [comment] 2020-01-20 15:00
I'd be happy to look at this. Please could you assign it to me? thanks

**Comment by dannyparsons** [comment] 2020-01-21 13:58
@lloyddewit This message box appears, which is generated in the RLink. The first check would be to see what is triggering this.
I believe it should be able to cope with deleting all the data frames, whether you do it through Close File or deleting all the data frames.
It may be that the RLink is not recognising that all the data frames are gone and is trying to access something that isn't there. Or possibly the empty `Data Book` is not returning the correct information from the R side.

![image](https://user-images.githubusercontent.com/11214914/72810499-c3f67700-3c6e-11ea-8863-9f9db8b00e51.png)

**Comment by lloyddewit** [comment] 2020-01-23 15:23
@dannyparsons Thank you for the extra information.
The R code generated by dlgDeleteDataFrames looks correct:
```R
data_book$delete_dataframes(data_names="diamonds")
```
As described above, this seems to work correctly unless the last data frame is deleted. In this case, the grid still displays the last data frame's data and displays the error message box.

The message box is triggered in `clsGridLink.UpdateGrids` line 135. The conditions that trigger the message box are:
```vb
        If frmMain.clsRLink.bInstatObjectExists Then
            'various operations and checks that don't trigger errors ...
            ':
            If (bGrdDataExists AndAlso (bGrdDataChanged OrElse bRDataChanged)) OrElse (bGrdVariablesMetadataExists AndAlso (bGrdVariablesMetadataChanged OrElse bRVariablesMetadataChanged)) Then
                expTemp = frmMain.clsRLink.RunInternalScriptGetValue(clsGetDataNames.ToScript(), bSilent:=True)
                If expTemp IsNot Nothing Then
                    lstDataNames = expTemp.AsList
                Else
                    If Not bMessageShown Then
                        MsgBox("Error: Could not retrieve data frames from R. Data displayed in spreadsheet may not be up to date." & Environment.NewLine & "We strongly suggest restarting R-Instat before continuing.", MsgBoxStyle.Exclamation, "Cannot retrieve data")
                        bMessageShown = True
                    End If
```
Note that all the booleans checked above are `true` apart from `bRDataChanged` and `bRVariablesMetadataChanged` (which are false).

As you mentioned, `File/Close Data File` deletes all the data frames, and does not display the error message. The R code generated from RLink.CloseData is:
```R
# Closing data
rm(x=data_book)
# Creating New Instat Object
data_book <- DataBook$new()
```
The error message is not generated because `File/Close Data File` does not call the R code directly. Instead it calls `clsRlink.CloseData` which manually sets `bInstatObjectExists` to false before running the script:
```vb
        bInstatObjectExists = False
        RunScript(clsRm.ToScript(), strComment:="Closing data")
```

The simplest way to solve the issue would be:
- make the `dlgDeleteDataFrames` OK button call a vb subroutine (rather than direct R code)
- add the following logic to the vb subroutine:
```
if ucrSelectorDataFrames is empty
    RLink.CloseData()
else
    run delete data frames R code
```
However, the OK button is part of a ucrBase user control. I could not see how to link a vb subroutine to the OK button.

Questions:
- Is the above approach OK?
- Is there a way to make the OK button call a vb subroutine?
  - I noticed that the OK button in the options dialog calls a vb subroutine. This is a standard button, not a ucr control. Is this the best approach?

Thanks for your help.

**Comment by dannyparsons** [comment] 2020-01-23 18:35
@lloyddewit thanks for looking into this. It has reminded me that our code is a little messy around the use of `bInstatObjectExists`. I don't quite like the way we use:
```VB
bInstatObjectExists = False
RunScript(clsRm.ToScript(), strComment:="Closing data")
bInstatObjectExists = True
```
in closing the `data_book` since it relies on developers knowing when to set this manually (and causes issues like this bug if it's not set!). I think it would be better if this is done more automatically within `clsRlink`/`clsGridLink` to avoid these bugs. I don't think this needs to be addressed right now though, as it's not causing this issue.

This particular bug is caused by `bInstatObjectExists` being `True` when the code is assuming that if it is `True`, it exists and it has at least one data frame, as you noticed. When we just delete the last data frame, the `data_book` still exists as a variable in R, but it has no data frames inside.
On line 97 we could add an additional check to see if there is at least one data frame in the `data_book`, in addition to checking it exists. There is a `data_book` method called `data_book$dataframe_count()` so we could add a check that this is greater than `0`.
I would suggest doing this through adding a new `Public Sub` in `clsRLink` since we might use this function again. There are some similar examples in `clsRLink` of running a common `data_book` method and returning the output that you could use as a template.

I prefer this solution than modifying the actions on the OK button of ucrBase for the dialog since it keeps the consistency of how the OK button manages passing R code, and it also means that if we did introduce others ways of deleting all data frames outside this dialog, then the `clsRlink`/`clsGridLink` solution prevents this bug reappearing.

Let me know if you need any guidance.

**Comment by lloyddewit** [comment] 2020-01-24 10:16
@dannyparsons Thanks for the feedback, I agree this is a much better approach. I will make a pull request.

**Closed** 2020-01-24 13:39 UTC
Labels: Menu: Prepare, bug
