### ISSUE TITLE
Display of daily data dialog

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3515] opened 2017-06-30 10:28 UTC
I hope this is now easy as it is an example of a table with just column margins.  It would still be of interest if initially it was without margins.  It will (usually) just be presenting the data – rather than summarising, so it is also an example of tabulation display from already summarised data.

**Comment by dannyparsons** [comment] 2017-08-11 16:15
duplicate of #3067

**Closed by dannyparsons** 2017-08-11 16:15 UTC
Labels: Climatic, enhancement
