### ISSUE TITLE
Small error on the Position control when using the same dialogue with different data-frames

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7076] opened 2021-12-22 20:30 UTC
The Position control in this dialogue does not update, when the data frame is changed.

The default position is after the variable being selected.

I used the dialogue with the rice survey data and multiplied the yield, by 67.25 to put them into kg per ha  It gave an error mentioning a variable Distance (from a previous data frame.  I forced it to work, and then moved to another data frame.  Again the error, this time mentioning the yield from the survey data.

**Comment by anastasia-mbithe** [comment] 2022-01-13 08:50
@rdstern Hello, I have been trying to look into this issue using different data frames, interchanging them in the dialogue, but I have not been able reproduce the error. It seems to be working well from my side.

**Comment by anastasia-mbithe** [comment] 2022-01-26 06:35
Hello @rdstern, am still not able to reproduce the error, can you check if you still getting it from your end.

**Comment by rdstern** [comment] 2022-01-26 06:58
Go into R-Instat and Open from Library
a) Open sleep from the mosaic package
b) Return to the last dialogue and open the other file from mosaic, called Mustang I think.
c) Use your transform and standardise the variable Price into Price1.
d) Click on Position button and put it before Price.  Press ok.  All works fine
e) Now go to your dialogue again, and use the sleep data frame
f) Use the variable words - still (say) standardise and press OK

![image](https://user-images.githubusercontent.com/11226469/151117105-37023f0e-007d-4034-87fd-87efb198cb8a.png)

**Comment by dannyparsons** [comment] 2022-01-26 15:39
@Patowhiz Could also help here.

**Comment by N-thony** [comment] 2022-01-26 16:23
> Go into R-Instat and Open from Library a) Open sleep from the mosaic package b) Return to the last dialogue and open the other file from mosaic, called Mustang I think. c) Use your transform and standardise the variable Price into Price1. d) Click on Position button and put it before Price. Press ok. All works fine e) Now go to your dialogue again, and use the sleep data frame f) Use the variable words - still (say) standardise and press OK
> 
> ![image](https://user-images.githubusercontent.com/11226469/151117105-37023f0e-007d-4034-87fd-87efb198cb8a.png)
> 
> By the way this may be nothing to do with your dialogue. It could be a more general problem with the Position control?
> 
> So, I have now checked with the Prepare > Calculate dialogue, doing the same thing. I get the error there too. So it is a clearing problem with the Position control and not to do with a particular dialogue. I have changed the title.
> 
> It would be good to fix this for the forthcoming release, but it may be a bit difficult. It could well need advice from @shadrackkibet . So please investigate, but don't take too long before asking for help if you are not clear how to proceed.

But also the options under `Numeric` option are not resetting correctly to the default control when clicking on `Reset` button
![image](https://user-images.githubusercontent.com/68591383/151203382-6139a34c-4203-4971-a798-17f0cf27d07f.png)

**Comment by Patowhiz** [comment] 2022-02-01 05:09
I'm investigating this.

**Comment by Patowhiz** [comment] 2022-02-03 07:02
@anastasia-mbithe @rdstern @dannyparsons  I can confirmed that this problem is on the ucrSave control. And all dialogs that use this control have the bug explained by @rdstern.

The code below is responsible for this bug. The algorithm relied on 1 flag to determine when to change the adjacent column. 
@anastasia-mbithe I'll fix this in a separate PR and you may test, possibly with your PR too.

Thanks

```
Private Sub LinkedReceiverControlValueChanged(ucrChangedControl As ucrCore)
        If Not sdgSaveColumnPosition.bUserSelected Then
            bInsertColumnBefore = False
            If ucrLinkedReceiver.IsEmpty Then
                strAdjacentColumn = ""
            Else
                If TypeOf ucrLinkedReceiver Is ucrReceiverMultiple Then
                    strAdjacentColumn = ucrLinkedReceiver.GetVariableNamesList()(ucrLinkedReceiver.GetVariableNamesList().Length - 1)
                Else
                    strAdjacentColumn = ucrLinkedReceiver.GetVariableNames()
                End If
            End If
        End If
        UpdateAssignTo()
    End Sub
```

**Comment by Patowhiz** [comment] 2022-02-03 08:09
Instead of making changes to the `LinkedReceiverControlValueChanged()` event handler, I decided to just reset the position variables in the data frame change event. It made more sense to me that as that was the 'original' cause of the bug.

**Comment by rdstern** [comment] 2022-02-03 08:15
@Patowhiz great that you are mixing R-Instat with your climsoft work.
Just a check on the concept for the change you made.  When I go into a new data frame and then use a dialogue, for the first time, in that data frame, then some dialogues have their own default - often after the variable being used in the corresponding command.  Others - like Enter, don't always have such a variable, so, for them it is the End.

Are you saying that now the Position in a new data frame will always have end - so the default will now be ignored?

I'll check, but perhaps you know!

**Comment by Patowhiz** [comment] 2022-02-03 08:43
@rdstern thanks for the good question.

All position defaults for the dialogs have not changed. 

For instance dialogs that have their defaults after the variable used will behave the same. However, if as a user I had changed the position of the column, then when I change the data frame selected, the new default will be 'end'. But now that you have asked it, I think for such dialogs the default should be after the variable used?

**Comment by Patowhiz** [comment] 2022-02-03 08:47
@rdstern all defaults should now be retained. Thanks

**Comment by lloyddewit** [comment] 2022-02-14 17:17
@rdstern 
From PR #7188 :

![image](https://user-images.githubusercontent.com/57253949/153913397-0512c15a-e20e-43af-81df-3444d98ece03.png)

Can this issue also be closed?

**Comment by rdstern** [comment] 2022-02-14 17:28
I assume it can be closed, but am getting a bit confused.  @Patowhiz can you confirm we can close?

**Comment by Patowhiz** [comment] 2022-02-14 18:59
@rdstern @lloyddewitI fixed the original issue bug at the position control level.
@rdstern @anastasia-mbithe please note that my fix didn't fix the other reset problems outline by @N-thony in the [comment](https://github.com/africanmathsinitiative/R-Instat/issues/7076#issuecomment-1022364507) above. @anastasia-mbithe I think your PR #7188 was aiming to fix that? If that is already fixed, @N-thony you could help test the new master changes.
@anastasia-mbithe to proceed with your PR #7188 all you needed is to get the new changes from the master. Thanks.

**Comment by N-thony** [comment] 2022-02-15 07:22
> 

@Patowhiz I think PR #7188 was closed and not merged. I have tested the new master changes but the problem is still there.

**Closed** 2022-02-17 07:05 UTC
Labels: bug, Menu: Prepare
