### ISSUE TITLE
Error message when using the Density Plot dialog in R-Instat 0.7.7 with French translation.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7672] opened 2022-07-28 19:49 UTC
When clicking on **Density Plot** (Climatic>Compare>Display Density Plot>Density/Ridges), an error message appears after clicking on ok as showing the figure below 

![image](https://user-images.githubusercontent.com/106779233/181623430-2e9f140c-58af-4e0e-9ec1-cf0eb5c18639.png)

**Comment by N-thony** [comment] 2022-07-31 05:51
I have tried to reproduce this but I couldn't with 0.7.6, 0.7.7, and the merged version
![image](https://user-images.githubusercontent.com/68591383/182012218-a631a3dc-d9ec-4616-a991-f4b06bf3d754.png)

**Comment by N-thony** [comment] 2022-07-31 06:48
@Vitalis95 what is to be fix here is to set the default value i.e `Count` in the `Statistiques input control`

**Comment by lloyddewit** [comment] 2022-08-01 09:39
@N-thony @Vitalis95 I could not recreate. The 'statistiques' options are now English text which I think is correct (because the text is used directly in the R `geom_density()` call). So I think this issue is fixed. Please can you confirm and close this issue if appropriate?
Thanks!

**Comment by N-thony** [comment] 2022-08-01 15:56
> 

@lloyddewit I think we need just to make the small change by setting `Statistiques input control` default value to `Counts` as before in version 0.7.4
![image](https://user-images.githubusercontent.com/68591383/182190058-65ed751a-cdd9-46d9-b040-a3abfe35b89a.png)

**Comment by lloyddewit** [comment] 2022-08-03 06:32
> @lloyddewit I think we need just to make the small change by setting `Statistiques input control` default value to `Counts` as before in version 0.7.4 ![image]

@N-thony Ok, understood. Please could you assign one of the developers for this? 
thanks

**Closed** 2022-08-03 10:37 UTC
