### ISSUE TITLE
climatic>prepare>climdexindices

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3349] opened 2017-06-14 14:34 UTC
I have been testing this dialog using samaru data with stations.This is having a bug here.Is it a problem with my data or what???

![image](https://user-images.githubusercontent.com/26301973/27137805-861e55fe-5127-11e7-83aa-190cbbb20a20.png)

**Comment by dannyparsons** [comment] 2017-06-14 15:00
duplicate of #3226

**Closed** 2017-06-14 15:00 UTC
Labels: bug, duplicate
