### ISSUE TITLE
Fix error or errors in Prepare > Numeric > Regular Sequence

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7199] opened 2022-02-04 06:17 UTC
I first found this nasty bug with an odd data set, but I can now generate it quite easily.  I am suggesting @Patowhiz to look reasonably generally at the code.
This is straight after starting R-Instat.  I open the standard survey data and use the Regular Sequence dialogue.  I put 40 as shown below, so the sequence needs to be truncated.  

![image](https://user-images.githubusercontent.com/11226469/152479623-7557c99a-430d-4ea6-b7a1-b78b16c03260.png)

Damn - it works.  On other occasions I have had an error that the resulting column must be divisible by the worksheet length. 

No matter.  I return to the dialogue and repeat - nothing changed, except R-Instat has made the name regular1.  Now I get this nasty error:

![image](https://user-images.githubusercontent.com/11226469/152480221-4ebf17a0-f8eb-427f-8e3e-bb7738271a74.png)

I press Continue.  Nothing has been generated into the output window.

Now when I return to the dialogue it says there is an invalid character in the name.
![image](https://user-images.githubusercontent.com/11226469/152480362-9b9006f9-714d-4bcd-ad62-1e022052460b.png)

I have experimented a bit more.  If I use the dialogue in an ordinary way, but put my own invalid names, then it traps this - which is good.  But I then tried with 36 replaced by 15, so the sequence has to be extended - and got the nasty error again.

Tried again with multiple columns generated of right length.  All ok.  Then made 36 into 18 - so still a multiple, and got the nasty error immediately.

**Comment by shadrackkibet** [comment] 2022-02-08 07:07
Assigning this @derekagorhom. He recently worked on this dialog, Derick could you first try to replicate the bug? then investigate the source of the bug - which line of code caused this? I would like you to report on your findings here.

**Comment by derekagorhom** [comment] 2022-02-08 07:49
> Assigning this @derekagorhom. He recently worked on this dialog, Derick could you first try to replicate the bug? then investigate the source of the bug - which line of code caused this? I would like you to report on your findings here.

Thank you @shadrackkibet , i will look into it

**Comment by Patowhiz** [comment] 2022-02-08 10:43
@shadrackkibet thanks for assigning this to @derekagorhom. @derekagorhom I had already looked at this, I hope my findings below will save your time in fixing the bug.

@rdstern I agree that the 'Ok'  button should not be enabled when the 'To' input is greater than the data frame length. That's a 
check that should be added.

@rdstern I looked into your error, the error is thrown at the `clsRScript`  of the `Rscript` library probably written by @lloyddewit.
The error is caused by an invalid R script when the dialog is reopened. This is due to the `each` parameter value being removed.
(@lloyddewit  I hope the system exception error thrown here is intentional, of course the script passed by the dialog to the object is not valid).

**Script produced when you reopen the dialog**. 
```
# Code generated by the dialog, Regular Sequence
regular1 <- rep(x=seq(from=1, to=40, by=1), each=, length.out=36)
data_book$add_columns_to_data(data_name="survey", col_name="regular1", col_data=regular1, before=FALSE)
```
Notice the `each` R parameter that lacks the value. @lloyddewit does that make the R script invalid from the `clsRScript`  class perspective?

**Error thrown**
![Rscript_error](https://user-images.githubusercontent.com/21179007/152970571-0883d901-57b9-412d-9f7d-259338310078.PNG)

@derekagorhom fixing the `each` R parameter value, which is passed by `ucrNudRepeatValues` control, should fix the bug.

**Comment by lloyddewit** [comment] 2022-02-08 11:12
@Patowhiz Thanks for the analysis above. 
`RScript` is only intended to work with valid R script. If invalid R is passed to `RScript`, then the behaviour is undefined. `RScript` does not guarantee to detect all invalid R, but if does detect something invalid then it throws an exception.
I think this is the correct behaviour.

**Comment by Patowhiz** [comment] 2022-02-08 11:37
@lloyddewit thanks for the response. I agree that's the correct behavior. 

_More out of scope question below_

For detected invalid R like in this case, should it have given a hint about the `each` parameter value missing? As a developer using the library, I would expect the class to give me a hint  about the invalid R and possibly point out the exact invalid `token` I guess that may not have been a  priority to implement, if so the `undefined` behavior seems fine, the comment clearly explained it.

**Comment by derekagorhom** [comment] 2022-02-08 12:06
To fix the bug i changed the original code to 
 ucrNudRepeatValues.SetParameter(New RParameter(" ", 1)) 
and it is working fine now.

**Comment by Patowhiz** [comment] 2022-02-08 12:10
> To fix the bug i changed the original code to ucrNudRepeatValues.SetParameter(New RParameter(" ", 1)) and it is working fine now.

@derekagorhom that's interesting. I wonder why. And did the dialog produce the correct R script? I presume the `each `parameter name needs to be shown as part of the script.

**Comment by derekagorhom** [comment] 2022-02-08 12:12
> > To fix the bug i changed the original code to ucrNudRepeatValues.SetParameter(New RParameter(" ", 1)) and it is working fine now.
> 
> @derekagorhom that's interesting. I wonder why. And did the dialog produce the correct R script? I presume the `each `parameter name needs to be shown as part of the script.

Yes it works now. it didnt send the previous error roger was encountering

**Comment by derekagorhom** [comment] 2022-02-08 12:17
> > To fix the bug i changed the original code to ucrNudRepeatValues.SetParameter(New RParameter(" ", 1)) and it is working fine now.
> 
> @derekagorhom that's interesting. I wonder why. And did the dialog produce the correct R script? I presume the `each `parameter name needs to be shown as part of the script.

sorry @Patowhiz can you give your skype ID so that we can have a meeting

**Comment by rdstern** [comment] 2022-02-08 12:18
@derekagorhom sounds promising.  Are you going to do a pull request>

**Comment by Patowhiz** [comment] 2022-02-08 12:19
@derekagorhom probably, I would guess that if you change the `each` parameter value, the script produced should be invalid. You now have a control that is writing a parameter value without a parameter name to the general script, in principle the overall script should be invalid.

**Comment by derekagorhom** [comment] 2022-02-08 12:22
> @derekagorhom probably, I would guess that if you change the `each` parameter value, the script produced should be invalid. You now have a control that is writing a parameter value without a parameter name to the general script, in principle the overall script should be invalid.

yes i just realized it, i did not change the repeat value so it seem to work fine. thanks for the correction

**Comment by Patowhiz** [comment] 2022-02-08 12:22
@derekagorhom I can email you my skype id. thanks.

**Comment by derekagorhom** [comment] 2022-02-08 12:23
> @derekagorhom I can email you my skype id. thanks.

agorhomderrick@gmail.com

**Comment by Patowhiz** [comment] 2022-02-08 14:26
@rdstern after discussing with @derekagorhom we found what was causing the invalid bug, it is line 182 of `dlgRegularSequence`;
`ucrNudRepeatValues.AddAdditionalCodeParameterPair(clsSeqDateFunction, ucrNudRepeatValues.GetParameter(), iAdditionalPairNo:=1)`

![param_error](https://user-images.githubusercontent.com/21179007/153000634-d401cb40-e13c-4390-9800-3f4ed6c2eb48.PNG)

As shown above, the parameter pair is technically the same object(by reference). This gives the unexpected behavior that leads to the parameter value lacking in the final script produced. (@lloyddewit @dannyparsons  I did a quick find by reference and found some other dialogs have similar code, Based on my understanding of the base code, I would expect the parameter passed to be a clone of itself instead of a reference of itself?).

@rdstern a quick fix would be to either passing a clone of the parameter or creating a new parameter object, see code below;

**Quick fix**
` ucrNudRepeatValues.AddAdditionalCodeParameterPair(clsSeqDateFunction, ucrNudRepeatValues.GetParameter().Clone(), iAdditionalPairNo:=1)`
or 
` ucrNudRepeatValues.AddAdditionalCodeParameterPair(clsSeqDateFunction, New RParameter("each", 1), iAdditionalPairNo:=1)
`
However after exploring the dialog further, we found out the following;
Currently the dialog produces these commands;

For numeric sequence
```
regular <- rep(x=seq(from=1, to=36, by=1), each=3, length.out=36)
data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
rm(regular)
```
For date sequence
```
regular <- rep(x=seq.Date(from=as.Date(x="2018/1/1"), each=1, to=as.Date(x="2018/12/31"), by="1 days"), each=1, length.out=36)
data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
rm(regular)
```

@rdstern notice the `each` parameter inside the `seq.Date`. That parameter is from the repeat values control. We looked into [seq.Date](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/seq.Date) R command and found it didn't have the `each` parameter. We wonder why it's needed in this dialog? If not needed then the fix would be to remove the code that adds it in the dialog.

@rdstern looking at the [seq.Date](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/seq.Date) much further, we realised it's no longer different from [seq](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/seq) command. In fact the 2 functions accepts the from and to  as dates. `seq.Date` seems to be deprecated when you look at the documentation, we wonder why its being used in this dialog?
The 2 commands below will have the same output, so should we just simplify the dialog and use `seq` function even for dates?;
```
regular1 <- rep(x=seq.Date(from=as.Date(x="2018/1/1"), to=as.Date(x="2018/12/31"), by="1 days"), each=1, length.out=36)
regular2 <- rep(x=seq(from=as.Date(x="2018/1/1"), to=as.Date(x="2018/12/31"), by="1 days"), each=1, length.out=36)
```

@rdstern your response will determine how @derekagorhom will fix the bug and improve the dialog. Thanks.

**Comment by dannyparsons** [comment] 2022-02-09 14:58
@Patowhiz @derekagorhom Thanks for looking into this.

1. Parameters being shared by controls.
`.GetParameter()` is intended to be used if two controls need to refer to the same parameter (by reference). So this is in the intended behaviour. If not, you should use `New RParameter("each", 1)`. This is safer, so unless it's certain that the parameters should always be identical, use `New RParameter` instead.

2. `each` parameter
`each` is a parameter of `rep` not of `seq`. In your commands it is correctly in `rep` and works as intended from my checking.

3. `seq.Date` and `seq`
Short answer: We probably should switch to `seq` for the Date option too.
Long answer: But not for the reasons you mentioned.
`seq.Date` isn't depreciated. `seq.Date` is the implementation of the `seq` function for Dates. In R terms, `seq.Date` is the method for `seq` for objects with class `Date`. And in R if you call `seq` with a `Date` object it dispatches to the `seq.Date` method, so `seq` and `seq.Date` does the same thing if `from` is a `Date` object. This is how R does OO-Programming which is very different to most other languages. If you really want to know the details you can read all about it here! https://adv-r.hadley.nz/s3.html
It's normally advised to use the generic method and let R determine the correct method to dispatch to. So to follow standard practice we probably should use `seq` for the Date option too, but it makes no difference to what function is actually called.

**Comment by Patowhiz** [comment] 2022-02-10 09:43
@dannyparsons thanks for the response and the interesting R article (it's about time I read R in detail).

@derekagorhom please fix the bug based on @dannyparsons response.

@derekagorhom  also note that, you will fix the R commands produced (the `each` parameter is only for `rep`) and also simply used the `seq` function for dates.

**Comment by lloyddewit** [comment] 2022-02-10 11:05
> @lloyddewit thanks for the response. I agree that's the correct behavior.
> 
> _More out of scope question below_
> 
> For detected invalid R like in this case, should it have given a hint about the `each` parameter value missing? As a developer using the library, I would expect the class to give me a hint about the invalid R and possibly point out the exact invalid `token` I guess that may not have been a priority to implement, if so the `undefined` behavior seems fine, the comment clearly explained it.

I created  [issue #6 in the RScript repo](https://github.com/lloyddewit/RScript/issues/6).

**Comment by Patowhiz** [comment] 2022-02-10 21:22
@rdstern I found another inconsistency when I looked at the dialog further.

I loaded the dialog for the first time and clicked Ok, it produces the following command;

```
regular <- seq(from=1, to=36, by=1)
data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
```

Then I returned to the dialog and just changed the repeat values from say 1 to 2, it produces the following command and threw the shown error. Also the preview was not shown;

`rep(x=data_book$get_columns_from_data(data_name="survey", col_names="regular1"), each=2)`

![regular_seq_second](https://user-images.githubusercontent.com/21179007/153497683-707fd016-8070-43da-a87b-2d2e355f5a1c.PNG)


@derekagorhom @rdstern  Could you confirm that you get the same error?
These errors are somehow related and can be fixed by PR #7217 . 
@rdstern I presume that at any point, the dialog should have the `rep` as it's base function? I'm happy we have a skype call to explain what I mean, would be useful in helping us understand why there is a deliberate intention in the code to produce the different commands as shown above.

**Comment by derekagorhom** [comment] 2022-02-11 03:56
> @rdstern I found another inconsistency when I looked at the dialog further.
> 
> I loaded the dialog for the first time and clicked Ok, it produces the following command;
> 
> ```
> regular <- seq(from=1, to=36, by=1)
> data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
> ```
> 
> Then I returned to the dialog and just changed the repeat values from say 1 to 2, it produces the following command and threw the shown error. Also the preview was not shown;
> 
> `rep(x=data_book$get_columns_from_data(data_name="survey", col_names="regular1"), each=2)`
> 
> ![regular_seq_second](https://user-images.githubusercontent.com/21179007/153497683-707fd016-8070-43da-a87b-2d2e355f5a1c.PNG)
> 
> @derekagorhom @rdstern Could you confirm that you get the same error? These errors are somehow related and can be fixed by PR #7217 . @rdstern I presume that at any point, the dialog should have the `rep` as it's base function? I'm happy we have a skype call to explain what I mean, would be useful in helping us understand why there is a deliberate intention in the code to produce the different commands as shown above.

Yes @Patowhiz i am encountering the same error you have, even when i undo the commented code in line 140 it still gives me that error.

**Comment by derekagorhom** [comment] 2022-02-11 04:26
i did alittle digging and found out where the inconsistency is coming from, it happens to be in `data_object_R6.R` 
on` line 669 to 673`

```
#A bug in sjPlot requires removing labels when a factor column already has labels, using remove_labels for this if needed.
DataSheet$set("public", "get_columns_from_data", function(col_names, force_as_data_frame = FALSE, use_current_filter = TRUE, remove_labels = FALSE, drop_unused_filter_levels = FALSE) {
  if(missing(col_names)) stop("no col_names to return")
  #if(!all(col_names %in% self$get_column_names())) stop("Not all column names were found in data")
  if(!all(col_names %in% names(private$data))) stop("Not all column names were found in data")
  
```

**Comment by Patowhiz** [comment] 2022-02-11 09:31
@dannyparsons yes it's at the dialog level. I just wanted to know from @rdstern  if the different R commands produced was intentional, the code had suggested it was intentional From his and your response, @derekagorhom and I can now fix both bugs and refactor the code responsible for this.

**Comment by dannyparsons** [comment] 2022-02-14 12:28
No that was deliberate. The user doesn't need to worry about the sign, they just specify the step and the dialog works out if it should be positive or negative.

> Going by current logic, we now have an Rscript that has values different from what are being displayed to the user in dialog.

This is exactly the reason why we have R-Instat! So that the user interface can be simple even if the R code is complex. We choose the options which are logical to the user and then translate this into R code. If this doesn't match the arguments of the R function, then that's the job of the dialog to do that translation. If we only mirrored the arguments in the R code we would end up with very complicated and hard to use dialogs in some cases.

**Comment by Patowhiz** [comment] 2022-02-14 13:26
@rdstern you had a different view from @dannyparsons above [comment](https://github.com/africanmathsinitiative/R-Instat/issues/7199#issuecomment-1039030195) from our last online call. PR #7231 has those views. Let me know your new thoughts too once you have a look at it. Thanks.

**Comment by dannyparsons** [comment] 2022-02-14 14:20
I don't think it's a big difference, but to me "In steps of" is always a positive number, and would make most sense from a user perspective. It's sensible to use negative numbers for the `by` parameter as that makes the R code efficient. But I don't want to require users to know that they need to enter a negative number in this field, or change things automatically. I think keeping it positive simplifies usage.

In any case, I don't think it will be too confusing as the preview shows what's going to be in the output.

**Comment by rdstern** [comment] 2022-02-14 16:25
@Patowhiz I am happy to accept @dannyparsons arguments.  And, in general, I am really happy with his inputs to R-Instat.  We are getting into a very good place with the software!

**Closed** 2022-03-31 09:40 UTC
Labels: bug, Menu: Prepare
