### ISSUE TITLE
Improve speed of check for uniqueness in define climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6269] opened 2021-03-14 21:52 UTC
With very long datasets (e.g. 5 million rows) that you can easily get from the satellite data, the check for uniqueness seems very slow - i.e. other things took a bit of time, but I had to abort R-Instat after perhaps an hour.

There must be a way of doing this check faster?

**Comment by dannyparsons** [comment] 2021-03-17 13:48
I've checked this but I can't obviously find it being slow consistently. I tried with some large data sets and it takes ~30 seconds but always finishes. There is possibly an issue here but we need to have a reproducible example.

**Comment by dannyparsons** [comment] 2021-03-19 12:03
Closing this issue as we can't replicate. Please re-open if the issue is discovered again.

**Closed by dannyparsons** 2021-03-19 12:03 UTC
Labels: Climatic
