### ISSUE TITLE
Errors in R-Instat repeat the previous command 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5577] opened 2019-11-16 15:29 UTC
I think this is a general "feature".

I am getting it with the calculator when results are going to the output window.

For example 
2 + 3 
 gives 5 in the output window.
Then do 2 + x (where there is no x).  It gives an error.  Then it repeats the previous result, i.e. 5 from the command 2 + x.  That's a bit confusing!

**Comment by lloyddewit** [comment] 2020-01-26 11:58
@dannyparsons I think this bug is caused by the following:

- `RLink.RunScript(...)`, line 570
  - Calls `Evaluate(...)` with the R script (e.g. `.temp_val <- capture.output(2+x)`)
  - `Evaluate(...)` returns `True` if script executed successfully, else `False`
  - Line 570 ignores the return value
- `RLink.RunScript(...)`, lines 571-577
  - Extracts and displays the value of `.temp_val`
  - If the script was not successful then `.temp_val` still contains its previous value (or is potentially undefined)

I suggest to fix by:

- line 570: Check the return value of `Evaluate(...)` 
- If `True` then extracts and display the value of `.temp_val`
- Else do nothing

Do you have any feedback/suggestions? If you're happy with the suggested fix then please could you assign this issue to me? I'll then make a pull request. Thanks

**Comment by dannyparsons** [comment] 2020-01-27 05:37
@lloyddewit thanks, that looks correct to fix this.

I also suggest adding this line:

`Evaluate("rm(" & strTempAssignTo & ")", bSilent:=True)` 

after `expTemp = GetSymbol(strTempAssignTo)`

`rm()` removes the variable from memory in R. With your fix this this probably shouldn't be needed as well, but I like it to keep the R environment tidy and so we keep track of variables and remove variables after using them.

**Comment by rdstern** [comment] 2020-01-27 12:37
It still seems to repeat.  Here is my first example.
Go into R-Instat.
Open from library and open the Instat data from the Intro guide called survey
Then go to Model > Hypothesis tests
use the command cor(Fert,Yield), which runs fine.  Can use Try first to check.
then add 2, so cor(Fert,Yield2) which gives an error on Try.
Persist and it gives the error - good.  But it still repeats the previous result.

**Comment by dannyparsons** [comment] 2020-01-27 14:01
Ah, that's not fair :) that's a different bug than the one causing the output to display from the calculator!

The difference is that Hypothesis dialog, and others, are saving an object in the `data_book`, so we also have an issue of not extracting the wrong object from the `data_book` when the command gives an error. I hadn't noticed that this was also an issue, which is a different part of the code. 
I'm having a look at that now.

**Closed** 2020-01-29 08:30 UTC
Labels: Menu: Prepare, question
