### ISSUE TITLE
Script window - extra bracket added?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4444] opened 2018-03-08 17:42 UTC
I think this is a bug in the operation of the script file.  It occurred when I ran a command that was split over 2 lines.  It seems to add an extra bracket.

I think I have seen this before, but assumed it was me, and so fiddled with the number of brackets myself.

Here is the example - it is from the **openair** package.  I think that is one of the packages we have as part  of R-Instat, though it may just be that I have added it myself?  That would be good to check too.  

The commands in the openair pdf were as follows:

**data(mydata)
calendarPlot(mydata, pollutant = "o3", year = 2003)
calendarPlot(mydata, pollutant = "o3", year = 2003, annotate = "wd")
calendarPlot(mydata, pollutant = "o3", year = 2003, annotate = "ws",
cols = "heat")**

I changed it simply by adding openair::, as follows:
**data(openair::mydata)
openair::calendarPlot(openair::mydata, pollutant = "o3", year = 2003)
openair::calendarPlot(openair::mydata, pollutant = "o3", year = 2003, annotate = "wd")
openair::calendarPlot(openair::mydata, pollutant = "o3", year = 2003, annotate = "ws",
cols = "heat")**

I ran it a graph at a time.  The last command doesn't work.  But it does if you put the last command on only a single line.

**Comment by dannyparsons** [comment] 2018-03-12 13:20
This is an interesting one. It's because from the script window it's trying to capture the output of each line (to be able to display in the output window. Since each line is being treated separately it think brackets are missing. I think if it wasn't trying to capture output for the output window it would work correctly.
At the moment it always tries to capture output because even if there isn't any it doesn't matter. But here is an example where it's causing a problem. We could have an option in the script window of whether it does this or not, although the option might not make any sense. And if you turn this off then you can't get output into the output window.

**Comment by rdstern** [comment] 2018-03-12 15:07
In discussions on a possible continuation character for R commands over multiple lines it seems there isn't one.  But one solution suggested is to put the whole command in a bracket.  Then when you get to the end of a line, the bracket isn't closed.  Curly bracket is suggested I think too.

I wonder if that would help us here.  It is still ordinary R and perhaps R-Instat could check for that?

**Comment by dannyparsons** [comment] 2018-03-12 15:12
No the issue isn't with R its just that in R-Instat it tries to capture the output of each line separately.

**Comment by rdstern** [comment] 2018-03-12 15:14
Yes and I was wondering if R-Instat could check for a not closed { and then assume it waits for the end of the next line!

**Comment by maxwellfundi** [comment] 2018-05-15 09:19
@dannyparsons  how do you think we can implement this?

**Comment by dannyparsons** [comment] 2018-05-15 14:33
We could implement detecting incomplete lines and then e.g. only running lines that are complete and run incomplete lines with the following lines. It would take a bit of work to implement and correctly detect "incomplete" R lines so I would put this as low priority and changed the milestone to ANYTIME. 
If there's a suggestion for something simpler that would also be useful then something might be able to get done sooner.

**Comment by maxwellfundi** [comment] 2018-05-16 06:11
Great, I think am happy with your suggestion and hope @rdstern is too.

**Comment by lloyddewit** [comment] 2021-03-09 11:31
@rdstern I think I fixed this in PR #5796. In any case, I cannot recreate the error above.
Please could you test and close if you think its resolved? thanks

**Comment by lilyclements** [comment] 2022-07-18 12:09
@rdstern I think this is fixed and this PR can be closed, but, I might be testing wrong since I didn't know about the original issue!

**Comment by lloyddewit** [comment] 2022-10-23 10:25
This is now fixed so I will close.

**Closed by lloyddewit** 2022-10-23 10:25 UTC
Labels: bug, log_script window
