### ISSUE TITLE
The rainfall and temperature quality control dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4649] opened 2018-06-02 06:36 UTC
They are now looking great.  But still to complete:

a) I cannot get the rainfall to work.  Even with a simple example for Dodoma (from library) checking just rain > 50mm it says:

**Error running R command(s)
Error in self$apply_instat_calculation(manipulation, curr_data_list, previous_manipulations) : 
  No data specified for calculation.
The error occurred in attempting to run the following R command(s):
.temp_val <- capture.output(InstatDataObject$run_instat_calculation(calc=rainfall_filter, display=FALSE))
OK**   

b) The rainfall enables OK even when there is no data in the rain control.  I first tried (accidentally) with the wrong data frame and it was happy to enable OK.

c) For the outlier option I think in rainfall and temperature the calculated column, logical column (and please check the calculation also) have to be completed?  I get the limits it uses (which I don't need, but would like the value of the offending observation (compared to the 1.5 say).  And I don't think the logical column for this case is yet connected?

Sorry for starting a new issue, but I couldn't easily find the original.

**Comment by bethanclarke** [comment] 2018-06-05 13:13
@shadrackkibet okay for me to start on this? Just want to check before I make any more conflicts!

**Comment by shadrackkibet** [comment] 2018-06-05 13:15
Yes, please go on.

**Comment by bethanclarke** [comment] 2018-06-05 14:12
I have fixed issue (a), it was due to grouping running without the parameter calculated_from. It was doing this because grouping should only run when we have Station selected but it was running when there was no variable for Station selected. 

However, that being said, if you have multiple options checked it still doesn't work, so I am currently looking into this

**Comment by dannyparsons** [comment] 2018-06-05 14:23
If it would help I am happy to look at the R code produced for the calculation to find the source of the remaining issues.

**Comment by bethanclarke** [comment] 2018-06-05 14:36
@dannyparsons thank you but I think I have figured out the problem! I am only have an issue when I have outliers checked along with another option and this is because of change that has been made recently, which is the options are being assigned and then used rather than going straight into the rain_filter function

**Comment by bethanclarke** [comment] 2018-06-05 20:34
Issues a) (for the most part!) and c) are fixed. 

I now have the outlier results assigned to outlier_test_calculation, the R-code is as follows:
```
grouping_month <- instat_calculation$new(type="by", calculated_from=list("Dodoma"="month_abbr"))
outlier_limit <- instat_calculation$new(type="calculation", function_exp="summary_outlier_limit(x=Rain, coeff=1.6, skewnessweight=2.8, bskewedcalc=TRUE)", calculated_from=list("Dodoma"="Rain"), manipulations=list(grouping_month), result_name="outlier_limit", save=0)
outlier_test_calculation <- instat_calculation$new(type="calculation", function_exp="Rain > outlier_limit", calculated_from=list("Dodoma"= "Rain"), result_name="Outlier", sub_calculations=list(outlier_limit), save=2)
rainfall_filter <- instat_calculation$new(type="filter", function_exp="Outlier", sub_calculations=list(outlier_test_calculation), result_data_frame="Rainfall_Filter", save=2)
InstatDataObject$run_instat_calculation(calc=rainfall_filter, display=FALSE)
```

Now the issue is when we have more than one option checked, for example Large and Outlier. The R-code produces a new data frame with the correct rain_fall filter, and the R-code runs in R no
problem:

```
# Code generated by the dialog, Climatic Check Data Rainfall
grouping_month <- instat_calculation$new(type="by", calculated_from=list("Dodoma"="month_abbr"))
outlier_limit <- instat_calculation$new(type="calculation", function_exp="summary_outlier_limit(x=Rain, coeff=1.6, skewnessweight=2.8, bskewedcalc=TRUE)", calculated_from=list("Dodoma"="Rain"), manipulations=list(grouping_month), result_name="outlier_limit", save=0)
outlier_test_calculation <- instat_calculation$new(type="calculation", function_exp="Rain > outlier_limit", calculated_from=list("Dodoma"= "Rain"), result_name="Outlier", sub_calculations=list(outlier_limit), save=0)
large_test_calculation <- instat_calculation$new(type="calculation", function_exp="Rain > 200|Rain < -1E-8", calculated_from=list("Dodoma"="Rain"), save=0, result_name="Large")
rainfall_filter <- instat_calculation$new(type="filter", function_exp="Large | Outlier", sub_calculations=list(outlier_test_calculation, large_test_calculation), result_data_frame="Rainfall_Filter", save=2)
InstatDataObject$run_instat_calculation(calc=rainfall_filter, display=FALSE)
``` 

But this error appears in R-Instat:
![rainqcissue](https://user-images.githubusercontent.com/16190039/41000839-34b2154a-6907-11e8-90f9-63b70cb9e0e5.PNG)

Is the issue something to do with the outlier observations being grouped by month and the Large observations are not? I will look into this first thing tomorrow.

**Comment by dannyparsons** [comment] 2018-06-06 10:01
There's no problem with the second calculation actually. It gives an error only when you run it after the first calculation. This is because you are trying to add the second calculation into the same data frame produced from the first calculation (because of `result_data_frame="Rainfall_Filter"`) and it can only add new data to an existing data frame if there is a key because it needs to merge the new data in. Or if you run the second calculation with a different data frame name it will work too.

I'm not sure what we should do about this generally. it would be good if the default data frame name checked that it is not an existing data frame to avoid this.

We could also add a key to the new data frame because Station and Date define a key in the filtered data, and then it would be able to correctly merge the data from a second calculation, if that's what we wanted.

**Comment by rdstern** [comment] 2018-06-20 16:48
In the outlier option, there are 2 problems we found.

a) It doesn't give a logical column (well 2, one for min and the other for max.
b) The option for the outliers has a default of 1.5.  Changing this value seems to have no effect.  I suspect the default is 1.5 and it is fixed at that value, because there are many values in the filter.  I tried with 2 and then changed it to 3 and got the same limits and the same number of outliers.

I only checked for temperatures.  In the data we are using I had 250 points in the filter from all the other settings and (currently) 750 from the outlier option.  

In the rainfall outliers I noticed there were some NAs in the limits.  I wondered why?

**Closed** 2018-06-28 09:41 UTC
