### ISSUE TITLE
Bad parameter message with new master on 21 Sept 2021

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6784] opened 2021-09-21 15:11 UTC
![image](https://user-images.githubusercontent.com/11226469/134197299-26ab7196-b442-4d30-970f-91fbbdab46c8.png)

This is the new message I get from the current master.  I try the new master regularly and this problem has just happened.  I tried twice and it is the same.

Clicking repeatedly goes into R-Instat, but the message appears regularly thereafter and also affects the appearance of dialogues. For example see below:
![image](https://user-images.githubusercontent.com/11226469/134197974-cbd45785-daf7-4483-b302-fbf3b41aa50b.png)

**Comment by shadrackkibet** [comment] 2021-09-22 06:20
This is a translation problem, @lloyddewit is best to advise.

**Comment by lloyddewit** [comment] 2021-09-22 07:48
@shadrackkibet I cannot recreate this issue. Please could you try?

**Comment by rdstern** [comment] 2021-09-22 07:56
I get it each time I use the master.  I am also getting it on the recent pull request on a wordcloud geom that (I assume) started with a recent master.  Would it help if I share my screen?

**Comment by lloyddewit** [comment] 2021-09-22 08:02
@rdstern You are getting the error 'bad parameter or other api misuse'. This is thrown by the translation library when it tries to execute an SQL 'Select' query. The exception could be thrown if the query is badly formulated, or there is a system problem that prevents the database from being accessed. 
I cannot recreate the error. This makes me think it's more likely to be a system problem rather than the SQL queries. To find out more we need to see if anyone else can recreate the error.

**Comment by lloyddewit** [comment] 2021-09-22 08:08
> 
> 
> I get it each time I use the master. I am also getting it on the recent pull request on a wordcloud geom that (I assume) started with a recent master. Would it help if I share my screen?

Sharing your screen could help. Unfortunately I have a deadline for the annual report today.

Please could you try running an older branch (e.g. from a PR merged at the start of September)? This will help show if it's a system problem rather than a problem caused by a recent PR merge.

**Comment by rdstern** [comment] 2021-09-22 10:23
I don't know if the location of the translation files helps.  I still have version 0.7.2 and 0.7.2.9000 (before the sprint) as well as the current version.  I now have 5 copies of the translation file, with extra copies starting yesterday - when the problems also started!  The full path to the one with the problem includes the debug!  

![image](https://user-images.githubusercontent.com/11226469/134313681-3147d6fe-7699-411a-98d6-c1765f4a3a8a.png)

**Comment by lloyddewit** [comment] 2021-09-22 11:25
@rdstern I don't think that's a problem. I can't see the full path names but what you have looks normal to me

**Comment by rdstern** [comment] 2021-09-23 06:05
@lloyddewit I seem to have resolved the issue.  It is at least partially due to my lack of understanding of the VB.Net environment.  I noticed that I had set a menu item to `Debug`.  When I changed that to `Release`, the problem went away!  Sorry for the panic!

**Closed** 2021-09-23 12:59 UTC
Labels: bug
