### ISSUE TITLE
Excel file that doesn't paste into R-Instat?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7095] opened 2022-01-11 11:36 UTC
@Patowhiz I would like to "promote" your dialogue Edit > New Data Frame and include it in the File > New dialogue.

But I am sending you separately and Excel file that I am finding difficult with the Paste.

I also tried with other Excel files and they worked fine.  

This one - from our evaluation of R-Instat - imports easily into R-Instat - all sheets if needed.  But when I do Paste New Data Frame it says as follows:

![image](https://user-images.githubusercontent.com/11226469/148935753-642492ca-8289-4dfc-b58c-0bafccdd3017.png)

**Comment by Patowhiz** [comment] 2022-01-13 15:43
@rdstern I'm looking into this.

**Comment by Patowhiz** [comment] 2022-02-03 12:39
@rdstern @dannyparsons this an interesting problem. Perhaps @shadrackkibet might have an explanation for this. 
Below are my findings after coping just 5 lines of the file that you sent to me.

When you use the copy data frame dialog, below is the command that gets sent to R.

```
.temp_value <- clipr::read_clip_tbl(x="Category	Feature	BlueSky	Deducer	JASP	jamovi	RAF	Rattle	Rcmdr	R_Instat	RKWard
Ease_of_Use	Operating Systems	2	3	4	4	3	3	3	1	3
Ease_of_Use	Simple installation	1	0	1	1	0	0	0	1	1
Ease_of_Use	Simple start-up	1	1	1	1	1	0	0	1	1
Ease_of_Use	Hides R by default to prevent ""code shock""	1	1	1	1	0	0	0	0	0
", header=TRUE, nrows=10)
```

The above code looks valid, however the problem is encountered in the escaped double quotes, for some reasons the underlying functions of `clipr::read_clip_tbl` is cannot pick the escaped double quotes. 
It gives me this error;
```
Error: unexpected string constant in:
"Ease_of_Use     Simple start-up 1       1       1       1       1       0       0       1       1
Ease_of_Use     Hides R by default to prevent ""code shock""
```

When I try to use the command below in RStudio that reads the data directly from the clipboard, below is the output;
**Command**
`clipr::read_clip_tbl(header=TRUE, nrows=10)
`

**Output**
```
     Category                                  Feature BlueSky Deducer JASP jamovi RAF Rattle Rcmdr R_Instat RKWard
1 Ease_of_Use                        Operating Systems       2       3    4      4   3      3     3        1      3
2 Ease_of_Use                      Simple installation       1       0    1      1   0      0     0        1      1
3 Ease_of_Use                          Simple start-up       1       1    1      1   1      0     0        1      1
4 Ease_of_Use Hides R by default to prevent code shock       1       1    1      1   0      0     0        0      0
```
Note that the output is **code shock** instead of **code shock**, I found this behavior weird, the `clipr::read_clip_tbl` literary changed the expected output. I wonder if the author did this intentionally.

When I change **"code shock"** to **'code shock'** both R-Instat and RStudio outputs change it to **'code shock'** .

Back to the problem, it's clear its the double quotes that are preventing R-Instat `R command`, the single quotes execute fine, so we could probably solve that, but the changed output bothered me.

**Comment by dannyparsons** [comment] 2022-02-09 15:40
@Patowhiz Very interesting, good spot to find this issue.

I had a little look at this. 

If you copy that text from your example then run `clipr::read_clip()` you get:

```r
clipr::read_clip()
[1] "Category\tFeature\tBlueSky\tDeducer\tJASP\tjamovi\tRAF\tRattle\tRcmdr\tR_Instat\tRKWard" 
[2] "Ease_of_Use\tOperating Systems\t2\t3\t4\t4\t3\t3\t3\t1\t3"                               
[3] "Ease_of_Use\tSimple installation\t1\t0\t1\t1\t0\t0\t0\t1\t1"                             
[4] "Ease_of_Use\tSimple start-up\t1\t1\t1\t1\t1\t0\t0\t1\t1"                                 
[5] "Ease_of_Use\tHides R by default to prevent \"\"code shock\"\"\t1\t1\t1\t1\t0\t0\t0\t0\t0"
```

So that's how you don't get this issue reading directly from the clipboard. (I guess that the `"` have to be removed to work in R objects, not too worried about losing them).

So I think what we need to do in VB before passing to R is essentially what `clipr::read_clip()` does to encode the data.

I don't think we need to go the full way of encoding all the symbols because it's only  `"` that's causing the problem.

So I think in VB you just need to replace `"` with `\"` in the clipboard text before passing it to `clipr::read_clip()`. Then we won't have this issue e.g.

```r
clipr::read_clip_tbl(x="Category	Feature	BlueSky	Deducer	JASP	jamovi	RAF	Rattle	Rcmdr	R_Instat	RKWard
Ease_of_Use	Operating Systems	2	3	4	4	3	3	3	1	3
Ease_of_Use	Simple installation	1	0	1	1	0	0	0	1	1
Ease_of_Use	Simple start-up	1	1	1	1	1	0	0	1	1
Ease_of_Use	Hides R by default to prevent \"\"code shock\"\"	1	1	1	1	0	0	0	0	0
", header=TRUE, nrows=10)
```

**Comment by Patowhiz** [comment] 2022-02-11 11:30
@dannyparsons thanks, that's what I had also had in mind.

@lloyddewit here is another bug at the `RScript `level. This is found when you use the **Paste New Data Frame** dialog, it's under the **Edit** menu. For some reason, the tokens fail to be retrieved correctly. Please note the R command is valid. And for that reason, the dialog as it is, cannot be used. You can also test it.

**Preview Output works correctly**

![no_error](https://user-images.githubusercontent.com/21179007/153583270-e7674843-e727-4e17-adac-d46da79ab334.PNG)

**On click Ok, `RScript` library fails to retrieve the R command tokens for the output.**

![erro1_details](https://user-images.githubusercontent.com/21179007/153583347-65129bfe-eb97-4879-a183-0cfcfffc4ea6.PNG)

@lloyddewit we can create a separate issue for the above bug. 
@rdstern I'm afraid you won't be able to test PR #7224 until the `RScript` bug is fixed

**Comment by lloyddewit** [comment] 2022-02-14 11:34
@Patowhiz Thanks for providing the extra information on the bug.
In `strScript`, there is a call to the `read_clip_tbl` function. This function sets the `x` parameter to a string. The string contains a newline character. I cannot see if it as Lf, Cr or CrLf.
In R, is it legal to put a line break in a literal string like this?
In R, if we want to specify a literal string containing a new line, is this the normal way to do it?

**Comment by dannyparsons** [comment] 2022-02-14 12:22
This is valid in R:
```r
x <- "fjkdsjkflsdkl
fklsdjfklsdf
fsdk"
```
It is the equivalent of:

`x <- "fjkdsjkflsdkl\nfklsdjfklsdf\nfsdk"`

where `\n` is for new line

**Comment by Patowhiz** [comment] 2022-02-14 13:08
@dannyparsons thanks for the informative feedback too.
@lloyddewit I'm not sure about your question exactly, probably we can look into that in a call together?
@lloyddewit what I do know is, if the overall script wasn't valid, the preview would not work, because the preview simply sends the entire R script to R via 'R-Instat', and the output of that command is shown in the grid.
The entire string parameter is from the clipboard as read by VB.NET. When you take the entire contents of the script with the `x` parameter contents, the R code still functions correctly, even when you use the script window of R-Instat.

**Comment by lloyddewit** [comment] 2022-02-14 18:46
@dannyparsons @Patowhiz 
I think you are both right, I don't think RScript copes with this newlines in literal strings. I raised an issue in the RScript repo. Let me investigate.

**Comment by Patowhiz** [comment] 2022-02-15 14:44
@lloyddewit the command below was recognised by the `Rscript `as **valid**. It has same new line string literals . And it's very similar, I think the token bug has something to do with the way the function is passed as a parameter. Not sure, I thought this information could help. I got this command from the Paste New Columns dialog that is in my PR #7224. Thanks.

```
# Code generated by the dialog, Paste Data to New Column(s)
data_book$paste_from_clipboard(data_name="survey", clip_board_text="SABEY	3	2
SABEY	13	5
SABEY	4	5
SABEY	20	1.5
SABEY	19	5
SABEY	10	4
SABEY	8	4.499999998
SABEY	11	3.5
SABEY	14	5
SABEY	12	4.499999998
KESEN	9	1.5
KESEN	8	7
KESEN	1	2.5
KESEN	4	8
KESEN	6	4.499999998
KESEN	3	2
KESEN	5	4
NIKO	2	4.499999998
NIKO	8	2.5
NIKO	7	6
NIKO	3	6
NIKO	4	8
NANDA	4	4.499999998
NANDA	2	3.5
NANDA	13	20
NANDA	21	4
NANDA	12	3
NANDA	24	6
NANDA	26	4
NANDA	8	3
NANDA	20	2.5
NANDA	14	2.5
NANDA	28	2
NANDA	25	4
NANDA	5	4.499999998
NANDA	9	1.5", first_clip_row_is_header=FALSE)
```

**Comment by Patowhiz** [comment] 2022-02-23 10:48
@lloyddewit here is another bug that @rdstern found when using climatic boxplot dialog in the current training. I think (very lightly) it has something to do with the `Rscript` not recognizing `>` and probably also `<` operators. @dannyparsons says it's a big issue(if so). 

**The dialog.** Works fine until when you check the "Omit Below" option
![boxplot_dialog](https://user-images.githubusercontent.com/21179007/155304300-1902d14c-4903-421d-ae21-f64900cd923d.PNG)


**The command produced.**
# Code generated by the dialog, Climatic Boxplot
```
Data <- data_book$get_data_frame(data_name="Data")
last_graph <- ggplot2::ggplot(data=Data %>% dplyr::filter(rain > 0.85), mapping=ggplot2::aes(y=rain, x=make_factor(""))) + ggplot2::geom_boxplot(varwidth=TRUE, coef=2) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text(angle=90, hjust=1, vjust=0.5)) + ggplot2::xlab(NULL) + ggplot2::facet_wrap(facets= ~ Name, drop=FALSE)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Data")
data_book$get_graphs(data_name="Data", graph_name="last_graph")
```

**The exception thrown.**
![boxplot_error](https://user-images.githubusercontent.com/21179007/155304334-085500a7-fb03-401c-8586-3cfee653883a.PNG)


Thanks

**Comment by dannyparsons** [comment] 2022-02-23 11:41
Yes this is an important bug. I don't think it's an issue with `>` and `<` not being supported in general as there are other places this is in use and seems to work. I would suggest putting this in a separate issue so it can be addressed sooner.

**Comment by dannyparsons** [comment] 2022-02-23 16:55
I get the same bug when typing this into the calculator: `ifelse(year_2 > 30, 1, 0)`. The error message seems to be slightly different depending on whether there are spaces around the `>`.
Also note that you don't get the error if you just use `year_2 > 30`.

So possibly it's caused by having an inequality inside a function that's the issue?

**Comment by rdstern** [comment] 2022-02-24 05:38
I followed @dannyparsons message and tried another ifelse statement in the calculator - very simple one - and got the same message.  I assume I am correct that this has become serious.  I have used both the rainfall boxplots (with the condition) in the past - without a problem - and also the ifelse.  What has changed recently that could have caused this?

**Comment by rdstern** [comment] 2022-03-09 16:59
@lloyddewit I checked this issue with @shadrackkibet as I understand it has come from the work done by you and Ivan, for David.  Ivan said he hoped you could look at this one.  Shadrack said it would be possible to copy out the offending lines instead, but clearly better to make the correction.

**Comment by lloyddewit** [comment] 2022-03-09 18:59
Message from @dannyparsons on 14 Feb: 

> Hi Stephen,
Just to say this issue is great to raise, but I would put it as non-urgent. This isn't a critical bug at all, and pasting is a rare feature in R-Instat. I know you have limited time, so I would suggest focusing on the OpenCDMS Python work and other more urgent R-Instat tasks, unless it's very quick. I wouldn't see any problem with this waiting until March before resolving.

I'm still busy with CDMS but I'll try and look at this issue in the coming weeks.
Thanks for your patience.

**Comment by rdstern** [comment] 2022-03-16 17:49
@dannyparsons this (serious?) bug does appear elsewhere too.  A new simple example is to open diamonds and the to do filter and filter from factors.  Choose any factor, then press return and it crashes in the same way.

I wonder what else doesn't work?

**Comment by rdstern** [comment] 2022-03-17 11:33
@dannyparsons so principal components analysis also doesn't work.  It is another instance that is ok in 0.7.3 but not in our current version.  I tried with the decathlon data from factominer - which we use in this dialogue.  Then input the 10 variables and it crashes in the same place as the others.

Given it isn't urgent, I am assuming that @shadrackkibet and @fran2or continue with version 0.7.4 for the stats climatology course.  Maybe they can document any other instance of this bug in this issue too.

**Closed** 2022-04-26 08:00 UTC
Labels: bug
