### ISSUE TITLE
Line plot has multiple plot bug in Version 5.1

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5431] opened 2019-07-18 07:05 UTC
**Describe the bug**
In the graphs you have the option of Single or Multiple y.  In the line plot:
a) Complete it with single - I think any x and y.  Then close. Then return to the dialogue it has lost the y and the multiple is now there.

Also the multiple still says Single - which is a bug on other graphics dialogues too.  And on the line plot there is a funny area added half into the control.

**Screenshots**
If applicable, add screenshots to help explain your problem, particularly of error messages.

![image](https://user-images.githubusercontent.com/11226469/61436397-984aab00-a932-11e9-82a0-d4bc6fab0427.png)

**Comment by Ivanluv** [comment] 2019-07-18 12:35
@dannyparsons  I think commenting of the `SetReceiverStatus()` on the load event of the 

`ucrVariablesAsFactors` is the cause of this bug

**Comment by maxwellfundi** [comment] 2019-09-04 07:27
This seems to have been fixed with #5432  from @Ivanluv

**Closed by maxwellfundi** 2019-09-04 07:27 UTC
Labels: Graphics, Menu: Describe, bug
