### ISSUE TITLE
Small change needed in probability/exceedance graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6111] opened 2020-12-06 19:01 UTC
The changes in the dialogue seem to have been hard work.

Now I hope this is a simple point to fix.  Currently when you use the Add points option it now also subtracts the lines!  

Here is what it used to do!

![image](https://user-images.githubusercontent.com/11226469/101289649-be0d7400-37f5-11eb-8b94-96fcf328db1b.png)

**Comment by N-thony** [comment] 2021-01-07 08:51
@rdstern this looks fine for me and I may fix it. Could you please explain to me more where the problem is? Thanks.

**Comment by shadrackkibet** [comment] 2021-02-21 12:02
This was fixed via the linked PR above.

**Closed by shadrackkibet** 2021-02-21 12:02 UTC
Labels: Climatic, Graphics, bug
