### ISSUE TITLE
Focus wrong when I return to a dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4250] opened 2017-11-26 05:22 UTC
This is a minor issue, but may be general.  I have suggested Maxwell, because I found it with a graphics dialogue. Could be Patrick to look quickly.  If you can't solve it immediately then ask David.

I explain with an example:
I. **Open from Library** and use Instat examples, introductory guide, **survey** data set.
2. Use **Describe > Specific > Line Plot**
3. Complete the dialogue with **y = Yield and x = Village** then go down to **Factor (Optional)**.
4. Notice you don't have any factors in your data set.  So **close and make Village and Variety into factors.**
5. **Return** to the dialogue.  The **cursor** is still in the Factor (Optional) field, but the active field - in turquoise - is the **Y variable**.  Clicking on the factor field does no good until you go out and then come back in again.

**Comment by maxwellfundi** [comment] 2017-11-27 06:48
I have found out this issue of focus. It appears only on dialogs we are using the ucrVariablesAsFactors. So we will look into that control to see why that is happening.

**Comment by Patowhiz** [comment] 2017-11-27 09:15
@maxwellfundi the dialogue works fine on my side. The only issue that I'm getting is; it fails to maintain its previous state, i.e If the last cursor focus was on Factor (optional) then on closing and opening the dialogue the focus and active field should be on the same Factor (optional) . Currently, on opening the dialogue the active receiver field is always the Y variable.

I'm not seeing this issue

> The cursor is still in the Factor (Optional) field, but the active field - in turquoise - is the Y variable. Clicking on the factor field does no good until you go out and then come back in again.

**Comment by maxwellfundi** [comment] 2017-11-27 09:18
@Patowhiz  I did not see the last issue too. But i looked at various dialogs and only those with ucrvariablesasfactor had the issue of having the focus on the ucrvariablesasfactor every time you reopen other than where it was.

**Comment by Patowhiz** [comment] 2017-11-27 09:49
@maxwellfundi yes thats true.

**Comment by Patowhiz** [comment] 2017-11-27 10:35
@maxwellfundi @dannyparsons @rdstern 

I have investigated this issue and I think I have found what is causing this issue for `UcrvariablesAsFactor`.
The image below is a snapshot of subroutine `SetReceiverStatus()` Which gets called implicitly every time you run `ucrVariablesAsFactorForLinePlot.SetRCode(clsRaesFunction, bReset)` . The `ucrVariablesAsFactorForLinePlot` sets itself as the receiver everytime that command gets executed. This happens for all dialogues that use `UcrvariablesAsFactor` control. This calls for modification of this control. 

![x](https://user-images.githubusercontent.com/21179007/33262582-c60ed602-d377-11e7-8d99-507745220f83.JPG)

**Comment by Patowhiz** [comment] 2017-11-27 10:48
@dannyparsons I propose we remove the statement that sets the controls as receivers in the `SetReceiverStatus()` subroutine. Since its already being done whenever  a call to `SetMeAsReceiver()` of the `UcrvariablesAsFactor ` is made. This will only solve the problem even for the other dialoguues though a call  to setting the `UcrvariablesAsFactor ` receiver will have to be manually done e.g 

 ```
Private Sub SetDefaults()  
        ucrVariablesAsFactorForLinePlot.SetMeAsReceiver()
 End Sub
```

**Comment by volloholic** [comment] 2017-11-27 11:23
@Patowhiz Well done for looking into this. By all means try commenting out those lines and observing the behaviour. I wonder whether it is time to relook at this code more generally. There is an underlying issue which relates to dealing with the stacked variable on the subdialogs ect. Happy to discuss, possibly when Roger is with you.

**Comment by Patowhiz** [comment] 2017-11-29 06:16
@volloholic @dannyparsons @maxwellfundi  After fixing the `UcrvariablesAsFactor` the dialogue functions as expected. However this calls for fixing other dialogues that use it as well. They will have to call 
`ucrVariablesAsFactor.SetMeAsReceiver()` in their `SetDefaults()` subroutine.

**Comment by dannyparsons** [comment] 2017-12-06 13:13
Calling `ucrVariablesAsFactor.SetMeAsReceiver()` should be done explicitly in `SetDefaults()` anyway so I'm happy with that.
I believe the reason this was being done in `SetReceiverStatus()` is so that when you click the button then the single/multiple receiver is automatically the current receiver. So I think you will lose this functionality by removing those lines, but it could be re implemented by moving the SetMeAsReceiver into the sub handling the button press. If that's done then I think this will be ok.

No one has yet commented on why this is only happening recently - none of the code in ucrVariablesAsFactors has changed recently and this problem has only appeared recently. 
I think this is about the translations again and the fact that having localisable forms means there's a slight change of order in how things are done on load, related to applying the resources, although I can't be sure this is the cause but it seems strange that this is a recent issue.

**Comment by Patowhiz** [comment] 2017-12-06 20:23
@dannyparsons  which button ? So far I have tested the dialogues that use this control and they are working fine on my side

**Comment by maxwellfundi** [comment] 2017-12-07 06:04
Patrick, if you look keenly on that control, there is a button on top of
the control which changes the control from single receiver to multiple
receiver.

**Comment by Patowhiz** [comment] 2017-12-07 07:39
Aha! now I understand what he meant. Working on it

**Comment by Patowhiz** [comment] 2017-12-07 08:20
@dannyparsons I have fixed and pushed the issue. It should work fine now.

**Comment by dannyparsons** [comment] 2017-12-07 14:57
Great will check that out.

**Closed** 2017-12-08 13:36 UTC
Labels: bug
