### ISSUE TITLE
Corrections needed in the new Tables dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7437] opened 2022-05-02 08:56 UTC
@Ivanluv in the (new combined) summary tables dialogue, I find the problem is likely to be caused by the changes in the selector control, and hence by @Patowhiz changes.

I think the selector control does not refresh when the receiver is changed, nor for other changes, like changing the class of data.  So this dialogue, and presumably others are not usable.

a) When I go to the summary button and the Variables receiver it only allows factors.  That's a change from version 7.4 and we need it to allow variables as I show in Version 0.7.4.
![image](https://user-images.githubusercontent.com/11226469/166209460-199d2573-7a3c-49d4-9769-33cd546e890a.png)

compare the above with your new version.
b) If I come back from Summary to Frequency after being in the Variables control no control seems to have the focus now.
c) Please check if there is more!

**Comment by Patowhiz** [comment] 2022-05-04 06:30
@rdstern in regards to the selector, did you test the dialog with the latest changes from the master?

**Comment by rdstern** [comment] 2022-05-04 06:52
@Patowhiz yes I did and have just shown to Ivan.  We think we know the problem.  It is when the data selector refreshes.  I think you will see immediately I show you, but I'll give an example.
a) With the usual survey data and the summary tables dialogue, the first receiver just has factors, but the second just has numeric type variables.  You get the factors ok, but still have the factors in the second receiver.
b) If I stay in the second receiver, then move to another data frame and back again, then I correctly have the numeric data in this receiver.  But, when I move back to the first receiver, I still have all the numeric variables, and now not the factors.
c) In the review data the first 2 variables are character, and the rest are numeric.  When I use the tables dialogue I get (correctly) no factors - because there are none.  Now I close and make the first 2 variables into factors.  Then I return.  It still doesn't refresh, so the dialogue remains as though there are no factors.

**Comment by Patowhiz** [comment] 2022-05-04 07:34
@rdstern in regards to the selector, the bug is caused by a very tiny increment loop error (my fault caused by juggling different programing languages at the same time). I would expect all developers to have missed it. I have now fixed it.
Thanks for the testing.

**Closed** 2022-05-04 15:54 UTC
Labels: bug, Menu: Describe
